### ISSUE TITLE
Screenshots/release notes for Fdroid & Google Play

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#1081]
F-Droid has a new release upcoming with a design overhaul: https://f-droid.org/posts/a-new-ux-6-years-in-the-making/

They allow adding screenshots and a teaser image, all info at https://eighthave.gitlab.io/fdroid-website/docs/All_About_Descriptions_Graphics_and_Screenshots/

We should add our usual screenshots. As teaser/background image we can use our standard background: https://github.com/nextcloud/server/blob/master/core/img/background.jpg

TODO
- [ ] generate new screenshots (with generic usernames / avatars)
- [ ] add screenshots
- [x] verify if there is a fallback for non-localized screenshots
- [ ] test the plugin / get fastlane working with transifex.
  - [ ] translate with transifex
- [ ] add 7" images to google play to get tag "developed for tablets"
- [ ] add corresponding 7" and 10" images

**Comment by AndyScherzinger** [comment]
Probably something for you @tobiasKaminsky since you are handling all things f-droid usually? 

I can cover anything media related 👍

**Comment by tobiasKaminsky** [comment]
There are two ways:
- put it directly in fdroid repo
- put it in our repo 

which one do we want to do?

**Comment by AndyScherzinger** [comment]
I'd say our repo 🎫

**Comment by jancborchardt** [comment]
Yup, our repo cause then we have the sources centrally. :)

**Comment by AndyScherzinger** [comment]
excatly my reason behind voring our repo :)

**Comment by tobiasKaminsky** [comment]
Currently testing it on dev.
As far as I understand it, fdroid will automatically use the icon / description if the folder structure is correct *finger-cross*

**Comment by tobiasKaminsky** [comment]
So finally I got it working on fdroid, tested only with dev version:
![fileqyhcte](https://user-images.githubusercontent.com/5836855/27673689-4e73b5f0-5ca2-11e7-947e-fac966a005dc.png)

Now the remaining problem is how to get this integrated to transifex: https://github.com/fastlane/fastlane/issues/9520

**Comment by tobiasKaminsky** [comment]
We should also use this for play store to have the description translated into all supported languages.

**Comment by LukeOwncloud** [comment]
Is this f-droid update related to the issue that the official release there is out of date? It is still 1.4.2 while playstore is already at 1.4.3 Even more curious : The more recent playstore version was uploaded in May, the older f-droid version in June.

**Comment by tobiasKaminsky** [comment]
No this is only about adding screenshots to fdroid, same as in play store.
With upcoming version 1.5 all will be in sync again.

**Comment by mario** [comment]
@tobiasKaminsky is this done? Can we close?

**Comment by tobiasKaminsky** [comment]
No, I tested it with one screenshot on dev version and it works.
Now I will need to do this for the official app (before 1.5 release).

**Comment by tobiasKaminsky** [comment]
Fastlane can also be used for translating the app descriptions.
The current drawback of fastlane is its cluttered string/text structure which makes it hard for transifex:
- fastlane
  - de-DE
    - full_description.txt
    - short_description.txt
    - title.txt
  - en-US
    - full_description.txt
    - short_description.txt
    - title.txt

There is a [plugin](https://github.com/JackyQu/fastlane-plugin-transifex) which may solve this. I have asked for clarification about this.

Another feature of fastlane is that this can also upload the translated descriptions and screenshots to gplay, so we would have all in one common place.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky what needs to be done here except new screenshots? Imho for a first release (for the next stable) I'd say it is enough to have the English master texts and the screenshots. What do you think?

**Comment by tobiasKaminsky** [comment]
First new screenshots, with dummy users, proper user names, nothing greyed out (e.g. use localhost/nc")

On a later approach: get transifex working with fdroid/fastlane.

**Comment by tobiasKaminsky** [comment]
I will do some new screenshots tomorrow morning.

**Comment by jancborchardt** [comment]
Yup, and let's make sure we do screenshots which show day-to-day use of the app and less settings / setup.

So for example:
- Nice grid view with photos
- List view with documents
- Auto upload view
- Sidebar
- Log in view or settings go _last_

Also cc @marinofaggiana for iOS since there we also need to reorder. :)

**Comment by tobiasKaminsky** [comment]
In transifex we have these strings (android-appstore-listing):

**Short description**
The Nextcloud Android app allows you to access all your files on your Nextcloud.

**Long Description:**
The Open Source Nextcloud Android app allows you to access all your files on your Nextcloud.

Features:
* Easy, modern interface
* Upload your files to your Nextcloud server
* Share your files with others
* Keep your favorite files and folders synced
* Instant Upload for photos and videos taken by your device
* Multi-account support

Please report all issues at https://github.com/nextcloud/android/issues and discuss this app at https://help.nextcloud.com ;-)

New to Nextcloud? Nextcloud is a private file sync & share and communication server. It is fully open source and you can host it yourself or pay a company to do it for you. That way, you are in control of your photos, your calendar and contact data, your documents and everything else.

Check out Nextcloud at https://nextcloud.com

---------
Reporting issues should be (changed url, no smiley):
Please report all issues at https://github.com/nextcloud/android/issues and discuss this app at https://help.nextcloud.com/c/clients/android

I would like to change/add features to (no big changes, but still):
* Easy, modern interface, fully themed to reflect your server (...?)
* Upload your files to your Nextcloud server
* Share your files with others
* Keep your favorite files and folders synced
* Search across all folders on your server
* Auto Upload for photos and videos taken by your device
* Keep up to date with notifications
* Multi-account support
* Secure access to your data with fingerprint or pin

**Comment by tobiasKaminsky** [comment]
Screenshots:
- Nice grid view with photos
- List view
 - different kind of mimetypes: image, pptx, zip, pdf, ...
 - folders: shared to user and via link
- Auto upload view
- Sidebar
- Log in view or settings go last

I can do them. I have created a dummy symlink on my computer so that all users now are part of "nextcloud.testserver.de".

Any suggestions about the images?

**Comment by tobiasKaminsky** [comment]
@mario @AndyScherzinger @jancborchardt 
please have a look at the two comments above regarding text and screenshots.
As 2.0 is somewhat "soon" I want to start with screenshots and text tomorrow. (Transifex may take some time)

Once we are fine with the screenshots I take on the mobile device, I will then take the same screenshots for 7" and 10" tablet.

**Comment by mario** [comment]
@tobiasKaminsky will take a look. In the mean time, please look at remaining 2.0 bugs :)

**Comment by AndyScherzinger** [comment]
Easy, modern interface, fully themed to reflect your server (...?) 
--> Easy, modern interface, fully themed in alignment with your server's theming

> Any suggestions about the images?

https://pixabay.com/en/photos/?image_type=photo&order=ec&orientation=horizontal&pagi=2 😃 
High resolution and nearly all of them are  CC0 Creative Commons -> Free for commercial use, No attribution required

> Are you fine with the screenhots?

Yes 👍

**Comment by jancborchardt** [comment]
Sounds all good! I would only add one feature:

- Integration with DAVdroid for easy setup of Calendar & Contacts synchronization

**Comment by tobiasKaminsky** [comment]
This are the screenshots, also in this order that I would upload to gplay/fdroid.

![screenshot_20170922_115621](https://user-images.githubusercontent.com/5836855/30739291-118b0c8c-9f8d-11e7-8766-2bb0aaf39548.png)

I managed to use "fastlane screengrab", so we can have these screenshots in many/all languages and in three "sizes": phone, tablet 7", tablet 10".

**Comment by tobiasKaminsky** [comment]
Transifex updated: https://www.transifex.com/nextcloud/nextcloud/android-appstore-listing/

**Comment by jancborchardt** [comment]
@tobiasKaminsky just some small feedback on the screenshots:

Order should be:
1. Picture grid (the most appealing first)
2. List view
3. Sidebar
4. Sidebar with accounts
5. Auto upload
The log in screen with server address can be cut, that’s not necessary to show.

Some details on screens:
- Picture grid: isn’t the default zoom level 3 pics next to each other? This seems a bit big
- List view: Let’s remove the vcard file and the zip – and instead put some pictures, so the preview function is also shown.
- Both sidebar screenshots don’t seem to have any files in the listing. Not that bad but a detail
- Auto upload: Let’s maybe also show that you can upload content from other apps? Maybe Signal, Facebook, etc

**Comment by tobiasKaminsky** [comment]
- Order is adjusted
- grid column default is 3
- list view now with picture and video preview
- auto upload with screenshots & whatsapp images

![image](https://user-images.githubusercontent.com/5836855/30742513-ba6af18a-9f99-11e7-96a0-7232c069a753.png)

**Comment by AndyScherzinger** [comment]
@jancborchardt @tobiasKaminsky wouldn't 4 columns be nicer since it would then be in alignment with the auto upload screen which uses 4 columns in portrait and 6 in landscape 💃

**Comment by jancborchardt** [comment]
Ok, 4 are also nice as 3 is still quite big.

Looks great otherwise @tobiasKaminsky! :)

**Comment by tobiasKaminsky** [comment]
![2017-09-22-142200](https://user-images.githubusercontent.com/5836855/30744229-701a50d2-9fa1-11e7-9be4-f5dabaae47ad.png)

**Comment by AndyScherzinger** [comment]
Actual state of the f-droid listing for the dev version:
![device-2017-12-12-103751](https://user-images.githubusercontent.com/1315170/33877458-b5c7c3dc-df28-11e7-97b1-aae640bbfae6.png)

Actual state for the stable version:
![device-2017-12-12-103942](https://user-images.githubusercontent.com/1315170/33877481-c7b8cf6e-df28-11e7-950e-8a34bf5f78e1.png)

**Comment by jancborchardt** [comment]
It would also be cool to have a screenshot for DAVdroid as I mentioned above: https://github.com/nextcloud/android/issues/1081#issuecomment-331112873 :)

**Comment by tobiasKaminsky** [comment]
What exactly should be shown on the screenshot?

![2017-12-12-155458](https://user-images.githubusercontent.com/5836855/33890985-fb2003a0-df54-11e7-9891-122c81de313e.png) or ![2017-12-12-155551](https://user-images.githubusercontent.com/5836855/33890993-fe6663e2-df54-11e7-9de6-59e40649bd52.png)

(the second one can be a bit trickier to get automated)

**Comment by jancborchardt** [comment]
The simpler version would be to grey out everything except that menu entry. The more complicated one with logo and text:
![sync greyed](https://user-images.githubusercontent.com/925062/33894440-4f042de4-df5e-11e7-800c-9cb737b03d09.png) / ![sync davdroid](https://user-images.githubusercontent.com/925062/33894461-5bc8b63a-df5e-11e7-91ab-7f1deb72e330.png)

What would be even better for the future are screenshots inside a mock-device with text above them for more description like we do in the iOS app: https://itunes.apple.com/us/app/nextcloud/id1125420102?mt=8 – the app-only screenshots generally seem a bit bland, and apps with more »speaking« screenshots seem more polished. :)

**Comment by tobiasKaminsky** [comment]
Greying out is somehow more complicate to do, but I guess it is possible.
Adding some space around a screenshot and show some text is working.

--> use left screenshot, grey out and add to all screenshots some nice text?

I want to have this automated to support all main languages.

![test](https://user-images.githubusercontent.com/5836855/33935786-7425a252-dffd-11e7-9ee3-5eae43dd6106.png)


Now we need short descriptions for those images:
![image](https://user-images.githubusercontent.com/5836855/30742513-ba6af18a-9f99-11e7-96a0-7232c069a753.png)

**Comment by jancborchardt** [comment]
Ok, sounds good! :) Some general points:
- Can we use a Nextcloud blue #0082c9 background instead of white? With white text
- Font should be Open Sans Light
- There can be more space for the text above (two lines) and the bottom part of the device (and even the screenshot) can be cut off

Descriptions for the images (without the part before the ":")
- Grid view: A safe home for all your data
- List view: Browse and share your files easily
- Menu: Quickly access activity, shares, offline files and more
- Multiaccount: Connect to different accounts
- Auto upload: Automatically upload your photos & videos
- DAVdroid sync setting: Sync Calendar & Contacts with DAVdroid

Sounds good @jospoortvliet @NinaNC?

**Comment by tobiasKaminsky** [comment]
> (and even the screenshot) can be cut off

have a look at the other screenshots, I do not think we should cut them off.

I can send you the svg if you want to polish it further.
![test2](https://user-images.githubusercontent.com/5836855/33946143-4603bab6-e021-11e7-8503-c967ab69d622.png)

**Comment by jancborchardt** [comment]
They need to be cut off because otherwise when you view them on a mobile device and the whole thing with text & device is fullscreen, the screenshot part of it will be much too small. Just cut off the lower quarter of the screen, really only the "add" button gets cut off.

Screenshots are for a quick impression and marketing and do not need to give a 100% exact full view. That's also why the explanatory text is more important than the pure screenshot.

**Comment by tobiasKaminsky** [comment]
What about this? 
If you (still) want changes, I am happy to give you the files so you can make a decent mockup/file out of it.

![01_grid_view_1513265031009](https://user-images.githubusercontent.com/5836855/34000153-bd82e6fe-e0ec-11e7-9512-6ff2b6271a11.png) ![02_list_view_1513265041669](https://user-images.githubusercontent.com/5836855/34000155-bda499ca-e0ec-11e7-80e5-fd6aea26b1f7.png)
![03_drawer_1513265038441](https://user-images.githubusercontent.com/5836855/34000156-bdc9024c-e0ec-11e7-9128-0a9e61c7189b.png)
![04_accounts_1513265044312](https://user-images.githubusercontent.com/5836855/34000158-bde9d936-e0ec-11e7-90a0-6ab1e0961145.png)
![05_auto_upload_1513265036599](https://user-images.githubusercontent.com/5836855/34000159-be20f592-e0ec-11e7-9dbe-504267ca5afb.png)
![06_davdroid_1513265033380](https://user-images.githubusercontent.com/5836855/34000162-be5b89aa-e0ec-11e7-8bf7-743d9301b46a.png)

**Comment by jancborchardt** [comment]
Hey na geil! :)

**Comment by NinaNC** [comment]
The description seems good! :)
Just one criticism: the purple theme is not very pretty with the blue background. The screenshots Jan uploaded had the right blue. If it's easy to modify, maybe it's worth changing? Or the purple theme has a specific meaning that I don't know about?

**Comment by jancborchardt** [comment]
Right - the screenshots should be completely unthemed defaults. :)

**Comment by tobiasKaminsky** [comment]
Uh. Right. When I do the "real" screenshots there will be only our Nextcloud colors.
Thanks for the hint :-)

**Comment by tobiasKaminsky** [comment]
@jancborchardt are you fin with the unthemed screenshots? 
Then I'll find some time to do them soon.

**Comment by jancborchardt** [comment]
Yeah, as commented above I agree they should be unthemed. :)

**Comment by tobiasKaminsky** [comment]
Status update: it is merged and we have to wait for translators to translate the 6 screenshot descriptions, otherwise we would have localized images but english descriptions.

**Comment by joshtrichards** [comment]
Closing. As it happens screenshots are currently missing from F-Droid, but that's covered in #3803. Also gplay updates via #8614.
