### ISSUE TITLE
Version 3.27 is not present on Google Play Store and F-Droid

### ISSUE THREAD

**Issue by louim-lbs** [nextcloud/android#12335]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Version 3.27 is not present on Google Play Store, only 3.26.

### Expected behaviour

Version 3.27 is present on Google Play Store.

### Actual behaviour

Version 3.26 is present on Google Play Store.

### Android version

NA

### Device brand and model

NA

### Stock or custom OS?

Stock

### Nextcloud android app version

NA

### Nextcloud server version

NA

### Using a reverse proxy?

I don't know

**Comment by regs01** [comment]
As well as F-Droid. I thought it wasn't finally released.

**Comment by varac** [comment]
Yes please update Fdroid and Play store, I'm waiting for this release in particular because it should fix an issue with auto-upload of photos/videos. Thanks !

**Comment by varac** [comment]
@gemorgan Are you subscribed to some GPlay beta/testing channel ? To me the link in the README.md (https://play.google.com/store/apps/details?id=com.nextcloud.client) still shows 3.26.0. Wonder where you found a published 3.27.0 ?

**Comment by regs01** [comment]
3.27.0 is not released yet.
#12229

Even 3.26.0 isn't released yet. Changes in F-Droid were not official.
#11735

**Comment by AndyScherzinger** [comment]
I was able to release 3.27 to Google Play from my phone @tobiasKaminsky since I am on vacation. 

For f-droid there are manual steps to take requiring a keyboard where a phone is not enough

So I expect devs to be able to take care of this next week. Sorry for the inconvenience 😞

**Comment by louim-lbs** [comment]
Thank you very much!
Should I let the issue open, waiting for the F-Droid release?

**Comment by AndyScherzinger** [comment]
Yes, please 👍

**Comment by regs01** [comment]
I kind of wondering - 3.27 seem to be merged to F-Droid data 3 days ago.
https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.nextcloud.client.yml

But it's still 3.26 in the repository. How is it working? How often repository gets refreshed?
https://f-droid.org/ru/packages/com.nextcloud.client/

**Comment by AndyScherzinger** [comment]
> How is it working?

F-droid staff members are manually publishing a new release to their store. So you would need to ping them on gitlab in order for somebody to take care of it

**Comment by AndyScherzinger** [comment]
Happy to hear f-droid published the release too 👍
