### ISSUE TITLE
Remove foreground worker for auto upload 

### ISSUE THREAD

**Issue by JonasMayerDev** [nextcloud/android#12954]
To help with reliability, we started using a foreground worker to scan the file system for changes. This is not good practice and we should try to get rid of the foreground worker since it leads to this [issue](https://github.com/nextcloud/android/issues/12596) for example.

The goal would be to change the auto upload mechanism to make it resumable (if the worker gets stopped by the system, it should not start scanning from scratch) and reduce the probability for the worker to get killed.

## TODO
- [X] Individual Worker for every Auto Upload Folder (https://github.com/nextcloud/android/pull/13015)
- - [x] Check if restarting all uploads all the time is necessary (every worker each time)
- - [x] Add a restart all method to FileSyncHelper 
- [ ] Make FileSyncWorker restartable without potential data loss (https://github.com/nextcloud/android/pull/13262)
- [ ] https://github.com/nextcloud/android/issues/13008 (https://github.com/nextcloud/android/pull/13262)
