### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [nextcloud/android#13170]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

https://gitlab.com/fdroid/fdroiddata/-/jobs/7165201279 Could you please take a look? Thanks!

### Expected behaviour

Build succeeds.

### Actual behaviour

Build fails.

### Android version

0

### Device brand and model

0

### Stock or custom OS?

Stock

### Nextcloud android app version

20240622

### Nextcloud server version

0

### Using a reverse proxy?

I don't know

### Android logs

https://gitlab.com/fdroid/fdroiddata/-/jobs/7165201279

**Comment by joshtrichards** [comment]
Appears fixed.
