### ISSUE TITLE
Release 3.30.1 - Roadmap

### ISSUE THREAD

**Issue by alperozturk96** [nextcloud/android#13678]
**Planned RC1: 07.10.2024**
**Planned Release date: 16.10.2024**

- [ ] Bump version code in ```build.gradle``` file
- [ ] release new library if needed
- [ ] release new SSO if needed
- [ ] Verify that the new version number is shown in settings
- [ ] Verify that logging is enabled
- [ ] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [ ] release with fastlane: creates GH release, uploads to Gplay, creates Gitlab MR for F-Droid
- [ ] Verify that it is shown on [F-Droid](https://f-droid.org/de/packages/com.nextcloud.client/) (within 24h)
- [ ] inform marketing about changelog and expected release date

**Final Release, after one weeks time (max) of latest RC release**
- [ ] Bump version code in ```build.gradle``` file
- [ ] release new library if needed
- [ ] Verify that the new version number is shown in settings
- [ ] Verify that logging is disabled
- [ ] Test that what's new is shown correctly on upgrade
- [ ] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [ ] release with fastlane: creates GH release, uploads to Gplay, creates Gitlab MR for F-Droid
- [ ] Verify that it is shown on [F-Droid](https://f-droid.org/de/packages/com.nextcloud.client/) (within 24h)

Backports:
- [App](https://github.com/nextcloud/android/milestone/99)
