### ISSUE TITLE
bump minSdkVersion to 26 (Android 8.0)

### ISSUE THREAD

**Issue by mahibi** [nextcloud/android#13865]
Percentage usage of android 7.0 for NC android files userbase is 0,45
For android 7.1 it's lower.

We have the rule to ditch android version lower than 0,5%.

# ToDo:

- [ ] remove checks for android versions older than api level 26
- [ ] bump minSdkVersion to 26
- [ ] update documentation at https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#mobile-apps

**Comment by mahibi** [comment]
same for android talk: https://github.com/nextcloud/talk-android/issues/4369
