### ISSUE TITLE
Release x.y.z - Roadmap

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#150]
- [ ] Bump version name and version code in AndroidManifest.xml
- [ ] Update CHANGELOG.md adding new features
- [ ] RC1: tag new version as rc-x.y.z-01 (YYYY-MM-DD)
 - [ ] Verify that the new version number is shown in settings
 - [ ] Build and release to Play Store as beta release and :shipit: 
 - [ ] Publish it on f-droid as optional release: edit metadata and open new merge request on gitlab
- [ ] After two weeks time (max) release as stable and replace screenshots (see updates ones here: https://github.com/nextcloud/screenshots/tree/master/android/phone)
- [ ] Tag new version as stable-x.y.z (triggers an f-droid release within 24h)
- [ ] Build and release to Play Store as stable release and :shipit:

**Comment by tobiasKaminsky** [comment]
Dummy roadmap used for all further releases.

**Comment by strugee** [comment]
@tobiasKaminsky a better way to manage the changelog would be to just require that all major PRs include an entry under an "Unreleased" header. Then "update CHANGELOG.md above" becomes just "change 'Unreleased' to have a version number and date."

And, as a bonus, then people have a preview of what's already been implemented for the next release.

/cc @AndyScherzinger @przybylski

**Comment by AndyScherzinger** [comment]
@strugee makes sense process wise. We also discussed this vs. the all-in-one approach. Both have their up and downsides. Pro: people have a preview of what has already been implemented for the next release (and got merged) Con: All PRs will then have a merge conflict in the changelog when updating to latest master (can be prevented by doing the changelog part right before the merge). Already implemented features for the next release can be seen anyways by checking the milestone (open/closed PRs).

What do you think @tobiasKaminsky ?

**Comment by tobiasKaminsky** [comment]
For me it does not matter. 
The idea of @strugee has the advantage that we make sure that we do not forget something in the changelog.

**Comment by AndyScherzinger** [comment]
If everything is properly assigned to a milestone we do have the list over there. That is what I used up to now to create the changelog entries. 
But it doesn't matter to me neither.
