### ISSUE TITLE
Release 3.0 - Roadmap

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1884]
Todo
- [x] https://github.com/nextcloud/android/issues/1837 Show message on refreshing if there is no connection
- [x] #1856 After first login: No new files
- [x] #1174 After first login: No new files
- [x] https://github.com/nextcloud/android/issues/1242 Support for Android 8.0
	- [x] #1887 Oreo support in app
	- [x] https://github.com/nextcloud/android/issues/1886 Oreo: Round app icon?
	- [x] https://github.com/nextcloud/android-library/pull/102
- [ ] #1081 Screenshots
- [x] #1881 Screenshots
- [x] #1869 New background for NC13
- [x] E2E
	- [x] https://github.com/nextcloud/android/pull/1944
	- [x] https://github.com/nextcloud/android-library/pull/92
	- Test upgrade from
    	- [x] 2.0.0
	    - [x] All e2e versions
- [x] Android library
	- [x] Merge https://github.com/nextcloud/android-library/milestone/34
	- [x] New Android lib release
- [x] https://github.com/nextcloud/ios/issues/452
- Bug fixing

Roadmap (to discuss)
- Feature freeze (only this time, next time we have a new release cycle): 22.12.
- Only E2E (#1598) & bugfixes should be merged afterwards
- RC1 at beginning of January
- Release end of January

- [x] Bump version name and version code in **all (3)** ```AndroidManifest.xml``` files
- [x] Update ```CHANGELOG.md``` adding new features

**Test app with all supported Android version**
- Access all activities
- Auto upload
- Upload / download files/folders
- Use external SD card
- What's new slides correctly shown on first start

All tests on
  - [ ] Android 4
  - [ ] Android 5
  - [ ] Android 6
  - [ ] Android 7
  - [ ] Android 8

**RC1**
- [x] Verify that the new version number is shown in settings
- [ ] Verify that logging is enabled
- [x] Tag new version as ```rc-3.0.0-01```
- [x] Build and release to Play Store as beta release and :shipit: 
- [ ] Publish it on F-droid as optional release: Edit metadata and open new merge request on GitLab
- [ ] Verify that it is shown on F-droid (within 24h)
- [x] Publish APK (generic) to https://download.nextcloud.com/android/

**RC2**
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is enabled
- [x] Tag new version as ```rc-3.0.0-02```
- [x] Build and release to Play Store as beta release and :shipit: 
- [x] Publish it on F-droid as optional release: Edit metadata and open new merge request on GitLab
- [ ] Verify that it is shown on F-droid (within 24h)
- [x] Publish APK (generic) to https://download.nextcloud.com/android/

**RC3**
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is enabled
- [x] Tag new version as ```rc-3.0.0-03```
- [x] Build and release to Play Store as beta release and :shipit: 
- [x] Publish it on F-droid as optional release: Edit metadata and open new merge request on GitLab
- [ ] Verify that it is shown on F-droid (within 24h)
- [x] Publish APK (generic) to https://download.nextcloud.com/android/

**Final Release, after two weeks time (max) of latest RC release**
- [x] Replace screenshots (https://github.com/nextcloud/screenshots/tree/master/android/phone)
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] update translations from transifex
- [x] Test that what's new is shown correctly on upgrade
- [x] Tag new version as ```stable-3.0.0```
- [x] Build and release to Play Store as stable release and :shipit: 
- [x] Update Play store changelog based on condensed ```CHANGELOG.md``` infos
- [ ] Verify that it is shown on F-droid (within 24h)
- [x] Publish APK (generic) to https://download.nextcloud.com/android/

@mario @AndyScherzinger

**Comment by AndyScherzinger** [comment]
👍

**Comment by tobiasKaminsky** [comment]
@mario @AndyScherzinger do we want to make some whats new screens?
Out of the features I would say
- End to end encryption
- Screen adapted images instead of downloading

**Comment by AndyScherzinger** [comment]
I agree with the list for what's new
- End to end encryption
- Screen adapted images instead of downloading

**Comment by mario** [comment]
What about IPv6 support pffF? :P

**Comment by tobiasKaminsky** [comment]
Then I'll do slides for those 3

**Comment by xXSTrikeXx** [comment]
Screen adapted images instead of downloading... :)

That sounds very cool

**Comment by xXSTrikeXx** [comment]
Screen adapted images instead of downloading... :)

That sounds very cool

**Comment by tobiasKaminsky** [comment]
3.0RC1 is now released on Google Play Store Beta Program and later this evening on Fdroid.

**Comment by xXSTrikeXx** [comment]
I dont know why exactly, but I miss the old icon. This one looks so narrow like a slimly built app and not like a big Cloud. :D Atleast I think its because of my sort order :D

**Comment by xXSTrikeXx** [comment]
I dont know why exactly, but I miss the old icon. This one looks so narrow like a slimly built app and not like a big Cloud. :D Atleast I think its because of my sort order :D

**Comment by tobiasKaminsky** [comment]
@xXSTrikeXx can you make a screenshot of it?
Here it fits quite well.
(But yes, there were some discussions about the icon)

![2018-01-18-120530](https://user-images.githubusercontent.com/5836855/35095192-e06526c0-fc47-11e7-8ec2-b2a4be1e9848.png)

**Comment by xXSTrikeXx** [comment]
I know :D and I havent something against it. It`s more my os that I think I need in next future a new mobile device :D In my case it looks like a seperation. :D I think its time for me using a newer android version :D

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @Bubu does any of you have any information/insight on if and when f-droid will be able to build and ship the 3.0.0 RC tags since 3.0.0 stable is kind of around the corner? No pressure, just asking!

**Comment by tobiasKaminsky** [comment]
RC3 is already in metadata, thanks to Marcus 👍 
Unforunately it seems that the buildserver has currently major hiccups...

**Comment by tobiasKaminsky** [comment]
Stable 3.0 is released on GPlay.
Fdroid will automatically fetch the new tag and build the new version.

**Comment by Bubu** [comment]
RC3 is built and released on fdroid as of yesterday.

**Comment by AndyScherzinger** [comment]
Nice @Bubu 👍
