### ISSUE TITLE
Release 3.1.0 - Roadmap

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2132]
As discussed, we want to release approx. every 2 months, so RC1 will be tagged at 23.03.18.

- [x] Bump version name and version code in ```build.gradle``` files
- [x] Update ```CHANGELOG.md``` adding new features
- [x] check if code is outdated due to last supported server version @NextcloudServer annotation

**Test app with all supported Android versions**
- access all activities
- auto upload
- upload / download files/folders
- use external sdcard
- what's new slides correctly shown on first start

**To be fixed**
- [x] #2439 
- [x] #2438 

**Translation update**
- [x] fetch latest transifex translations -> #2456

**merge PR** 
- [x] #2451
- [x] #2452
- [x] #2453
- [x] https://github.com/nextcloud/android/pull/2456

All tests on
  - [x] Android 4
  - [x] Android 5
  - [x] Android 6
  - [x]  Android 7

**RC1**
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is enabled
- [x] Tag new version as ```rc-3.1.0-01```
- [x] Build and release to Play Store as beta release and :shipit: 
- [x] Publish it on f-droid as optional release: edit metadata and open new merge request on gitlab
- [x] Verify that it is shown on f-droid (within 24h)
- [x] ~Publish APK (generic) to https://download.nextcloud.com/android/~

**RC2**
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is enabled
- [x] Tag new version as ```rc-3.1.0-02```
- [x] Build and release to Play Store as beta release and :shipit: 
- [x] Publish it on f-droid as optional release: edit metadata and open new merge request on gitlab
- [x] ~Verify that it is shown on f-droid (within 24h)~
- [x] ~Publish APK (generic) to https://download.nextcloud.com/android/~

**Final Release, after two weeks time (max) of latest RC release**
- [x]  replace screenshots (https://github.com/nextcloud/screenshots/tree/master/android/phone)
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] update translations from transifex
- [x] Test that what's new is shown correctly on upgrade
- [x] Tag new version as ```stable-3.1.0```
- [x] Build and release to Play Store as stable release and :shipit: 
- [x] Update Play store changelog based on condensed ```CHANGELOG.md``` infos
- [x] Verify that it is shown on f-droid (within 24h)
- [x] Publish APK (generic) to https://download.nextcloud.com/android/

**Comment by tobiasKaminsky** [comment]
TODO

Library
- [ ] review & merge all [outstanding PRs](https://github.com/nextcloud/android-library/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3A%222.+to+review%22)
- [ ] tag new release

App
- [ ] review & merge all [outstanding PRs](https://github.com/nextcloud/android/pulls?page=1&q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+milestone%3A%22Nextcloud+App+3.1.0%22+label%3A%222.+to+review%22)

@mario @AndyScherzinger

**Comment by tobiasKaminsky** [comment]
I went through all PRs that have "to review" label.
Most of them have already an approval by @AndyScherzinger, so they only need some approval by either @mario or @przybylski.
I will have a look into those PRs that require an approval by me this week.

Ideally we can merge the PRs soon so they are some time in dev version until RC1 is done next week on thursday.

**Comment by mario** [comment]
I commented on most PRs. Two big ones that I did not yet that need quite a lot of testing:

- device credentials
- recycler view

Please comment on questions where I've had them, and review my PRs.

**Comment by tobiasKaminsky** [comment]
As far as I can see in this ticket, we only have #2039 and #2372 left.

Good job :tada:

**Comment by mario** [comment]
What about the obey synced folder thing? Pls feel free to fix theming for
notificAtions

**Comment by tobiasKaminsky** [comment]
Andy and me tested it and it is not working. Rushing this in is a bit dangerous, or?
After lunch I'd like to do RC1.

**Comment by mario** [comment]
Ok

**Comment by tobiasKaminsky** [comment]
Two fixes found, if nothing new comes up, I will do RC2 tomorrow (29.03.)

**Comment by tobiasKaminsky** [comment]
RC2 released :+1:

**Comment by tobiasKaminsky** [comment]
Talked with Jos and planned is to release 3.1 on wednesday during hackweek :tada:

**Comment by tobiasKaminsky** [comment]
Backport
- [ ] https://github.com/nextcloud/android/pull/2164
- [ ] https://github.com/nextcloud/android/pull/2449
- [ ] fix for #2438

**Comment by AndyScherzinger** [comment]
- [ ] Also fetch latest transifex translations

**Comment by AndyScherzinger** [comment]
Added all open tasks to the main description

**Comment by AndyScherzinger** [comment]
Updated the closed todos.
@tobiasKaminsky can you also take care of publishing the apk on the Nextcloud download server? That'd be great :+1:

**Comment by AndyScherzinger** [comment]
@Bubu @tobiasKaminsky any idea why f-droid still hasn't published 3.1? Even owncloud which has been released days after our 3.1 release has been published already...

**Comment by tobiasKaminsky** [comment]
Ah, talked to Markus yesterday and also submitted a manual 3.1 merge request (https://gitlab.com/fdroid/fdroiddata/merge_requests/3093).

The problem is that fdroid tries to figure out the latest available version by parsing build.gradle.
Due to our newest semantic schemic version generation, this is currently not working any longer.
On IRC I got some hints, which will hopefully work.

**Comment by tobiasKaminsky** [comment]
I tried it without luck as their approach will not work for us, I fear. It is reading head/build.gradle to find out version code/name, but we have master and a release branch (e.g. 3.x). So master already have a "next alpha version"...

I fear we have to either revert the automatic generation or do the fdroid releases manually (which I prefer).
I will have a look into fastlane soon, which I want to use to automaticate building & publishing process to gplay and maybe this can also be used for fdroid to generate a merge request.

**Comment by AndyScherzinger** [comment]
I also prefer the manual way :+1:

**Comment by tobiasKaminsky** [comment]
I updated the generic release issue to reflect the manual fdroid way.

**Comment by tobiasKaminsky** [comment]
Now 3.1.0 is marked as latest version in Fdroid, so we are done here :tada:
