### ISSUE TITLE
Roadmap 3.0.2

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2230]
Outstanding
- [x] merge https://github.com/nextcloud/android-library/pull/126
- [x] tag & use new library
- [x] backport https://github.com/nextcloud/android/pull/2205
- [x] backport https://github.com/nextcloud/android/pull/2200
- [x] backport https://github.com/nextcloud/android/pull/2186
- [x] update transifex #2237 
- [x] Bump version name and version code in `build.gradle` files #2238

**Final Release**
- [x]  ~~replace screenshots (https://github.com/nextcloud/screenshots/tree/master/android/phone)~~
- [x] update Changelog.md #2238
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] update translations from transifex
- [x] Test that what's new is shown correctly on upgrade
- [x] Tag new version as `stable-3.0.2`
- [x] Build and release to Play Store as stable release and :shipit: 
- [x] Update Play store changelog based on condensed `CHANGELOG.md` infos
- [ ] Verify that it is shown on f-droid (within 24h)
- [x] Publish APK (generic) to https://download.nextcloud.com/android/

@mario @AndyScherzinger anything else?

**Comment by AndyScherzinger** [comment]
Nope, sounds good to me :+1:

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I updated the list to reflect the release todos.

**Comment by tobiasKaminsky** [comment]
3.0.2 is now released.

**Comment by tigernero79** [comment]
I had to disable e2e again because with the server-side encryption enabled and with e2e running via nextcloud 3.0.2 it is not possible to remove files in unencrypted folders. this is serious.

https://github.com/nextcloud/android/issues/2246
