### ISSUE TITLE
Release x.y.Z - Roadmap

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2287]
**Planned RC1: every second month in last week so that release is in first week of month / replace with date**
**Planned Release date:**

- [ ] Bump version code in ```build.gradle``` file
- [ ] release new library if needed
- [ ] release new SSO if needed
- [ ] Verify that the new version number is shown in settings
- [ ] Verify that logging is enabled
- [ ] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [ ] release with fastlane: creates GH release, uploads to Gplay, creates Gitlab MR for F-Droid
- [ ] Verify that it is shown on [F-Droid](https://f-droid.org/de/packages/com.nextcloud.client/) (within 24h)
- [ ] inform marketing about changelog and expected release date

**Final Release, after one weeks time (max) of latest RC release**
- [ ] Bump version code in ```build.gradle``` file
- [ ] release new library if needed
- [ ] Verify that the new version number is shown in settings
- [ ] Verify that logging is disabled
- [ ] Test that what's new is shown correctly on upgrade
- [ ] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [ ] release with fastlane: creates GH release, uploads to Gplay, creates Gitlab MR for F-Droid
- [ ] Verify that it is shown on [F-Droid](https://f-droid.org/de/packages/com.nextcloud.client/) (within 24h)

Backports:
- [App](https://github.com/nextcloud/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
- [Library](https://github.com/nextcloud/android-library/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

**Comment by joshtrichards** [comment]
Closing since this has no work tracking utility as-is and can still be used as a template while closed if desired.

**Comment by tobiasKaminsky** [comment]
Re-open as this is a template for your .1 releases
