### ISSUE TITLE
Roadmap: file detail & new sharing

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2485]
During hackweek @jancborchardt draw a new sharing system, which is nearly the same as web UI and which should then be also in sync with iOS.

* [x] Iteration 1 for File detail & new sharing #2533 (revamped UI approach)
* [x] Iteration 2 for File detail & new sharing #2573 (sharing in general)
* [x] Iteration 3 for File detail & new sharing #2671 (e-mail sharing permissions, details)
* [x] Iteration 4 for File detail & new sharing #2700 (create e-mail shares)
* [x] Iteration 5 for File detail & new sharing #2690 (comments)
* [x] Display copy icon and adding send action to the link menu #2730
* [x] Share link creation via bottom sheet for files in OCFileList #2747
* [x] implement #2742
* [ ] Add label/tag support - #11515
* [ ] Remove legacy sharing screen completely - TBD

Enhanced file detail view:
![detail](https://user-images.githubusercontent.com/5836855/38919147-102edd3a-42f0-11e8-8fcb-3b4403b27f6b.jpg)
This is an enhanced view for images/videos which have a preview:
- no overflow menu on top, but next to filename
- clicking on star toggles favorite
- tags opens up editing
- activity and sharing as "tabs" which can be toggled

Activity tab:
- combined activity, comments, versions (endpoint on server side is needed for this, https://github.com/nextcloud/server/issues/658)
- on top: text input box for commenting

Share tab:
![sharing](https://user-images.githubusercontent.com/5836855/38919558-32a34026-42f1-11e8-8c11-0b33347f3528.jpg)
- sharees are sorted by permissions (from max permissions to read only)
- on each sharee there is an overflow menu with its specific sharing permissions

Sharing to a new user/group/link:
- click on text input on share tab hides activity/sharing toggle to have more space for actually searching
- share link as entry beneath search field
	- with "can edit" 
	- click on it opens up existing app chooser to receive link
- during input we show the list of results
	- username
	- group
	- federated sharing
	- share by mail

![2018-04-18-102204](https://user-images.githubusercontent.com/5836855/38919944-5ed57262-42f2-11e8-8d79-1e14863440d3.png)
- share (left) -> opens up share dialog of file detail
- link (right) -> directly creates read-only link (if needed) and open list with apps to send to. "copy link" should be first entry as otherwise users might not find it (@schiessle)

cc: @rullzer @marinofaggiana for other clients

This is an overview issue, where I will link each PRs into it.
My plan is to do this step by step, so that each PR is rather small.

Of course any feedback is welcome :-)

**Comment by tobiasKaminsky** [comment]
Ref for comments: https://github.com/nextcloud/server/issues/7315#issuecomment-347468998

**Comment by AndyScherzinger** [comment]
So how would this be combined with commenting if we ever implemented commenting on files in the client?

**Comment by tobiasKaminsky** [comment]
Comments will shown in the activity tab, sorted by time, with version changes and other activities.
If you want to comment a file, a text input is always shown (see very first picture with "nice picture" and "right arrow").

**Comment by AndyScherzinger** [comment]
So will the current (webUI) master also merge activities and comments?

**Comment by tobiasKaminsky** [comment]
Yes, as mentioned above this is in issue https://github.com/nextcloud/server/issues/658

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky how will this look for now-previewable files?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky never mind, looked at the web ui and again... I need to ask and I feel have to phrase the question exactly like this to make a point: 
_Why is there a pen&paper mock-up when it is basically "please implement it exactly like the web ui"?_

**Comment by AndyScherzinger** [comment]
This is a (web)screenshot with the elements added...
![2018-04-25 14_53_52-files](https://user-images.githubusercontent.com/1315170/39247432-ae600b10-4899-11e8-86f1-61e0f5931b6d.png)

So how "Android native" does this feel for you?

cc @tobiasKaminsky @mario

**Comment by rullzer** [comment]
I agree. It should feel native to Android. And a copy of the webui doesn't feel that native. 

Maybe we can look at how other solutions do this and borrow from them?

**Comment by AndyScherzinger** [comment]
Both requests comments and tag support are described and covered in this issue, so the answer is yes :)

**Comment by AndyScherzinger** [comment]
Couldn't really find a nice way, but here is how it would be done mimicing the contacts app of Android (with a scrolling effect on the toolbar) while the activity items would probably be aligned, designed a bit different.
![details](https://user-images.githubusercontent.com/1315170/39273069-143f1090-48de-11e8-8a42-47848b90b64d.png)

![details2](https://user-images.githubusercontent.com/1315170/39273082-1a2c8d7a-48de-11e8-964f-0f56617a9f8e.png)

**Comment by Spartachetto** [comment]
@AndyScherzinger great! 
I think it will be an important improvement of the app.

To be honest I fail to understand how to tag the photo form the mockup you posted....

**Comment by AndyScherzinger** [comment]
> To be honest I fail to understand how to tag the photo form the mockup you posted....

via the tag/label icon in the toolbar

**Comment by Spartachetto** [comment]
Now I get it.

Thank you @AndyScherzinger for explaining it to me.
I am eager to try it!!! :blush:

**Comment by AndyScherzinger** [comment]
I had a talk with @tobiasKaminsky and we agreed on starting out with the given approach (since this will improve the functionality of the details screen a lot) while we still want the UI to be shaped towards a more native look&feel in comparison to the actual design mock up.

**Comment by AndyScherzinger** [comment]
Work in progress is PR #2533

**Comment by AndyScherzinger** [comment]
Updated the initial description to show all closed and open/pending PRs that are related to this big picture issue for new sharing/details view.

**Comment by Spartachetto** [comment]
Thank you all for the great work! Just one curiosity: "Add label support" means "Add tag support"?

**Comment by AndyScherzinger** [comment]
> "Add label support" means "Add tag support"?

Yes! :)

**Comment by pi-ken** [comment]
Yes.... Tags please!  I'm also assuming that once we can edit/add tags there will also be
a way to filter by tags, much like the desktop client.

**Comment by AndyScherzinger** [comment]
>  I'm also assuming that once we can edit/add tags there will also be a way to filter by tags, much like the desktop client.

I general yes, if it'll be available right away I can't say since that will be a different part within the app, but maybe @tobiasKaminsky has some insights :)

**Comment by BennyLi** [comment]
Moin. Are there any updates regarding the tags support?

**Comment by rplevka** [comment]
+1 to tag implementation. It's a thing blocking us from using the photo sharing properly.
I've been watching this roadmap for some time and see it's stale.
What is the issue? Can I help?

**Comment by AndyScherzinger** [comment]
> What is the issue? Can I help?

@rplevka The short version; 1) lack of dev capacity 2) yes
The slightly longer version: _If_ you could provide a PR with the implementation (exact solution might have to be discussed here upfront just to be sure the solution design gets approved) than I'd be positive it gets merged and the feature will be shipped. We are all here to help (answer questions, code reviews, discuss solutions, etc.).

**Comment by Spartachetto** [comment]
@AndyScherzinger thank you for your clear answers.

I came back to this issue because I happened to read https://github.com/nextcloud/server/issues/22435 

It could be useful to define better "Add label/tag support" . I am saying this because I honestly believed that some functionalities were already available and I had to open the app to see that this was not actually true.

Here is what I mean: it seems to me that _Add label/tag support_ can be split in three:

1. add / remove tags from a single file (like in the mock-up in https://github.com/nextcloud/android/issues/2485#issuecomment-384279509 )
2. search the files that have one or more tags (bonus points: and do not have other tags...)
3. perform some operations (copy, share, delete, ...) on the files that have one or more tags

While **_1_** should be totally dependent from the lack of enough developers, **_2_**  could maybe be solved by Unified search (for reference https://github.com/orgs/nextcloud/projects/38 , https://github.com/nextcloud/server/issues/21619, and hopefully https://github.com/nextcloud/server/issues/4851). 
No idea about **_3_**

**Comment by rplevka** [comment]
@AndyScherzinger - i'd add to _1_ that tag assignment should be possible on a selection of files too (bulk action). I think this is not even implemented in the web app as of today.

regarding my previous comment - It looks like I gave you some false hope there. The cruel reality is - i have no experience with android app development nor php.

**Comment by Spartachetto** [comment]
@rplevka for me that would be a point **_4_** because I think it needs a different interface, exactly like in the web interface where you can tag one single file but not a selection of files.

If @AndyScherzinger agrees and finds it useful, I could update the list above...

**Comment by Spartachetto** [comment]
Concerning Unified Search, it has been moved to OCS api: https://github.com/nextcloud/server/pull/22639

**Comment by AndyScherzinger** [comment]
I do find the split helpful, yes and would also agree with the assessment 👍

Looping in @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
Tags are currently not in our focus, as they are rarely used.

**Comment by joshtrichards** [comment]
> - Add label/tag support - https://github.com/nextcloud/android/pull/11515
> - Remove legacy sharing screen completely - TBD

This Issue seems done. Though I'm not sure what's meant by the last item re: legacy sharing screen. I suspect that is done too, but since I'm not certain I'll leave this open. Please close if unneeded any longer ;)
