### ISSUE TITLE
Release 3.2.1 - Roadmap

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2712]
- [x] Bump version name and version code in build.gradle files #2755
- [x] update Changelog.md #2755
	- [x] also update Changelog.md on master branch
- [x] ~~update translations from transifex~~
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] Test that what's new is shown correctly on upgrade
- [x] Tag new version as `stable-x.y.z`
- [x] Build and release to Play Store as stable release and :shipit: 
- [x] Update Play store changelog based on condensed `CHANGELOG.md` infos
- [x] Verify that it is shown on f-droid (within 24h)
- [x] Publish APK (generic) to https://download.nextcloud.com/android/

Backport PRs to be merged:
- [x] #2724
- [x] #2715 
- [x] #2739
- [x] #2743 
- [x] #2744
- [x] #2745
- [x] https://github.com/nextcloud/android/pull/2785
- [x] https://github.com/nextcloud/android/pull/2786
- [x] https://github.com/nextcloud/android/pull/2787
- [x] #2788

Library:
- [x] https://github.com/nextcloud/android-library/pull/154
- [x] make new 1.0.43.1 release (for next release we switch to semantic versioning, starting with 1.1.0)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you take care of publishing the apk on the download server
@tobiasKaminsky @Bubu any reason/idea why the 3.2.1 isn't published on f-droid yet?

**Comment by Bubu** [comment]
F-Droid is not publishing any apps right now. I'm pretty sure it's been built already for a few days though.

Working on it... :-/

**Comment by AndyScherzinger** [comment]
Thanks a lot for your efforts @Bubu :heart:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you publish the APK on the download server, so we get 3.2.1 finished up completely? :)

**Comment by tobiasKaminsky** [comment]
I gave the file to Roeland, he will take care of signing and uploading it.
