### ISSUE TITLE
Release 3.3.0 - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#2868]
- [ ] Bump version name and version code in build.gradle files
- [ ] update Changelog.md
	- [ ] also update Changelog.md on master branch
- [ ] update translations from transifex
- [ ] Verify that the new version number is shown in settings
- [ ] Verify that logging is disabled
- [ ] Test that what's new is shown correctly on upgrade
- [ ] Tag new version as `stable-3.3.0`
- [ ] Create maintenance branch as `stable-3.3.x`
- [ ] Build and release to Play Store as stable release and :shipit: 
- [ ] Update Play store changelog based on condensed `CHANGELOG.md` infos
- [ ] Verify that it is shown on f-droid (within 24h)
- [ ] Publish APK (generic) to https://download.nextcloud.com/android/

Backports:
- [app](https://github.com/nextcloud/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
- [Library](https://github.com/nextcloud/android-library/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

**Comment by AndyScherzinger** [comment]
Proposal for open PRs that should make it into 3.3.0 at this moment

* Add redirect info to external link #2864
* Clear file selection after performing various multi file selection actions - #2861
* Overlapping fab with snackbar #2823

What do you think @tobiasKaminsky ?

**Comment by tobiasKaminsky** [comment]
As always, I am more then fan of "everything that is ready, will be shipped".
Delaying a release for e.g. #2823 is not worth it, in my opinion.

**Comment by AndyScherzinger** [comment]
Fine with me :+1:

**Comment by AndyScherzinger** [comment]
I added another task: 

> provide new screenshots for an animated gif for https://nextcloud.com/install/#install-clients to @jospoortvliet  

since the screenshots are very old like the main menu has way more items now so I think i'd be nice to actually see that :)

**Comment by AndyScherzinger** [comment]
I think it would be nice if we could get the following PRs merged to master to be released with 3.3.0, that being:

* https://github.com/nextcloud/android/pull/2916
* https://github.com/nextcloud/android/pull/2887
* https://github.com/nextcloud/android/pull/2884
* https://github.com/nextcloud/android/pull/2881
* https://github.com/nextcloud/android/pull/2886 (file sync, tbd since it needs some testing)
* https://github.com/nextcloud/android/pull/2871 (Glide, tbd since it might need some more work)
* https://github.com/nextcloud/android/pull/2864

Any chance we can make this happen @tobiasKaminsky @mario @ardevd :pray: :heart:

**Comment by AndyScherzinger** [comment]
Further PRs to be merged prior to releasing RC1:
* [ ] #2944
* [ ] #2940
* [ ] #2935
* [ ] #1116

**Comment by AndyScherzinger** [comment]
3.3.0 has been released to the GPlay store, see blogpost https://nextcloud.com/blog/nextcloud-android-files-app-3.3-now-out-with-comments-media-streaming-and-trash-support/
with a huge thank you to:
:heart: @AndyScherzinger @ardevd @David-Development @jmintb @morvidus @tilosp :heart:

**Comment by tobiasKaminsky** [comment]
Also from me many thanks to our contributors (and especially @AndyScherzinger who feels like a full time colleague, but is doing it in his spare time :heart: )

**Comment by jmintb** [comment]
You were very welcoming and made it easy to contribute :)
