### ISSUE TITLE
Release 3.3.1 - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#3092]
**Test app with all supported Android version**
- access all activities
- auto upload
- upload / download files/folders
- use external sdcard
- what's new slides correctly shown on first start

All tests on
  - [ ] Android 4
  - [ ] Android 5
  - [ ] Android 6
  - [ ] Android 7
  - [ ] Android 8
_______

**Final Release**
- [x] Bump version name and version code in build.gradle files #3156
- [x] update Changelog.md #3156
	- [ ] also update Changelog.md on master branch
- [x] ~~update translations from transifex~~
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] Test that what's new is shown correctly on upgrade
- [x] Tag new version as `stable-3.3.1`
- [x] Build and release to Play Store as stable release and :shipit: 
- [x] Update Play store changelog based on condensed `CHANGELOG.md` infos
- [x] Verify that it is shown on f-droid (within 24h)

Backports:
- [App](https://github.com/nextcloud/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
- [Library](https://github.com/nextcloud/android-library/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

--------------------------
PRs to be merged prior to releasing:
_TODO_

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can we get this release please? :) It only fixes two issues, I know...but....the share type issue is the number 1 crash for the 3.3.0 release, so I think it would be nice to get this released since we already got this reported again even after the fix has been done but unfortunately not release yet :/

**Comment by tobiasKaminsky** [comment]
There is also a bug when Client is created on main thread, when entering Notification.
I'll have a look into this now and try to find a fix.
Then we can include this also.

**Comment by AndyScherzinger** [comment]
approved the PR :+1:

**Comment by tobiasKaminsky** [comment]
Backport is in #3154, after that I'll create a RC1 as I am not 100% if the fix is correct, as I cannot reproduce the error.

**Comment by AndyScherzinger** [comment]
Merged, since codacy is is also not a fan of non-master-targeting PRs... :/

**Comment by AndyScherzinger** [comment]
RC1 PR is #3156, todos have been updated

**Comment by tobiasKaminsky** [comment]
RC1 is released

**Comment by tobiasKaminsky** [comment]
RC2 needs this: https://github.com/nextcloud/android/pull/3114
Fix in #3154 seems to be ok.

**Comment by AndyScherzinger** [comment]
#3169 - 3.3.1 RC2

**Comment by tobiasKaminsky** [comment]
We should also include some kind of redo of the device credentials stuff.
Seems to be broken for quite a lot people.
(I will investigate further tomorrow)

**Comment by AndyScherzinger** [comment]
Sweet, sure thing. CI still isn't able to fetch all dependencies I guess some repo has issues, so we have to wait anyways :/

**Comment by AndyScherzinger** [comment]
CI is working again and as far as I can see, all fixes have been merged except for a potential, still to be implemented fix for device credentials.

**Comment by tobiasKaminsky** [comment]
I'll want to do RC2 today and on Monday/Tuesday 3.3.1 final, if no big issues occur.
Fingerprint is a tough one and I do not want to delay 3.3.1.
When fingerprint is working, we can do a quick 3.3.2.

**Comment by tobiasKaminsky** [comment]
3.3.1 RC2 is released, stable is planned for Monday/Tuesday.

**Comment by tobiasKaminsky** [comment]
Released: https://github.com/nextcloud/android/releases/tag/stable-3.3.1
Fdroid: https://gitlab.com/fdroid/fdroiddata/merge_requests/3877
