### ISSUE TITLE
Release 3.4.0 - Roadmap

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#3118]
Planned RC1: 26.11.18

**Create stable x.y.z branch & use it for release**
- [x] create branch ```stable-3.4.x```
- [x] make it protected
- [x] set up Codacy, Drone as required status
- [x] change ```drone.yml```
- [x] change ```getBranchName.sh```

**Bump**
- [x] release new library version & use this is in app #3310
- [x] Bump version name and version code in ```build.gradle``` files  #3310
- [x] Update ```CHANGELOG.md``` adding new features #3312 (master) & #3310 (stable)
- [x] check if code is outdated due to last supported server version ```@NextcloudServer``` annotation

**Test app with all supported Android version**
- access all activities
- auto upload
- upload / download files/folders
- use external sdcard
- what's new slides correctly shown on first start

All tests on
  - [x] Android 4
  - [x] Android 5
  - [x] Android 6
  - [x] Android 7
  - [x] Android 8

**RC1**
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is enabled
- [x] Tag new version as ```rc-3.4.0-01``` with private dev key (not on github)
- [x] Build and release to Play Store as beta release and :shipit: 
- [x] Publish it on f-droid as optional release: edit metadata and open new merge request on gitlab
- [x] Verify that it is shown on f-droid (within 24h)

**Final Release, after two weeks time (max) of latest RC release**
- [ ]  replace screenshots (https://github.com/nextcloud/screenshots/tree/master/android/phone)
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] update translations from transifex
- [x] Test that what's new is shown correctly on upgrade
- [x] Tag new version as ```stable-3.4.0``` with private dev key (not on github)
- [x] Build and release to Play Store as stable release and :shipit: 
- [ ] Update Play store changelog based on condensed ```CHANGELOG.md``` infos
- [ ] Publish it on f-droid as release: edit metadata, bump "current version" and open new merge request on gitlab
- [ ] Verify that it is shown on f-droid (within 24h)

**Comment by tobiasKaminsky** [comment]
TODO:
- [ ] integrate screenshots into fastlane

**Comment by tobiasKaminsky** [comment]
RC1 released on gPlay and fDroid :shipit:

**Comment by tobiasKaminsky** [comment]
RC2:
- [ ] backport of https://github.com/nextcloud/android/pull/3365

**Comment by tobiasKaminsky** [comment]
RC3 released, I forgot #3364.
