### ISSUE TITLE
Release 3.3.2 - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#3211]
**Test app with all supported Android version**
- access all activities
- auto upload
- upload / download files/folders
- use external sdcard
- what's new slides correctly shown on first start

All tests on
  - [x] Android 4
  - [x] Android 5
  - [x] Android 6
  - [x] Android 7
  - [x] Android 8
_______

**3.3.2 RC1**
- [x] Bump version name and version code in build.gradle files
- [x] ~~update translations from transifex~~
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] Tag new version as `rc-3.3.2-01`
- [x] Build and release to Play Store as RC release and :shipit: 
- [x] Verify that it is shown on f-droid (within 24h)

**Final Release**
- [x] Bump version name and version code in build.gradle files
- [x] update Changelog.md
	- [ ] also update Changelog.md on master branch
- [x] ~~update translations from transifex~~
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] Test that what's new is shown correctly on upgrade
- [x] Tag new version as `stable-3.3.2`
- [x] Build and release to Play Store as stable release and :shipit: 
- [x] Update Play store changelog based on condensed `CHANGELOG.md` infos
- [ ] Verify that it is shown on f-droid (within 24h)

Backports:
- [App](https://github.com/nextcloud/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
- [Library](https://github.com/nextcloud/android-library/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

--------------------------
PRs to be merged prior to releasing:
_TODO_

**Comment by tobiasKaminsky** [comment]
3.3.2 RC1 released on Gplay and Fdroid https://gitlab.com/fdroid/fdroiddata/merge_requests/3882 :shipit: 

Release will then be on Friday, as it only contains one fix and it is urgent to get this to users.

**Comment by tobiasKaminsky** [comment]
3.3.2 final released on Gplay and Fdroid 
https://github.com/nextcloud/android/releases/tag/stable-3.3.2
https://gitlab.com/fdroid/fdroiddata/merge_requests/3887

**Comment by AndyScherzinger** [comment]
Changelog on master is missing ;)
