### ISSUE TITLE
Release 1.4.0

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#332]
- [x] Bump version name and version code in AndroidManifest #424
- [x] Update CHANGELOG.md adding new features #424

**RC1** (https://github.com/nextcloud/android/tree/1_4_0_RC1)
- [x] Verify that the new version number is shown in settings
- [x] tag new version as rc-1.4.0-01 (2016-11-16)
- [x] Build and release to Play Store as beta release and :shipit: 
- [x] Publish it on f-droid as optional release: edit metadata and open new merge request on gitlab
- [x] Verify that it is shown on f-droid (within 24h)

**Final Release, after two weeks time (max) release**
- [x]  replace screenshots (https://github.com/nextcloud/screenshots/pull/28)
- [x] Verify that the new version number is shown in settings - #424
- [x] Tag new version as stable-1.4.0
- [x] Build and release to Play Store as stable release and :shipit: 
- [x] Verify that it is shown on f-droid (within 24h)

**Comment by iskradelta** [comment]
It would be nice to get the fix for logs not being made in the beta app into this release.

Im doing all this to solve the intermittent "Upload failed" error, sometimes its Connection error, sometimes just stalls at whatever percentage, once I saw it at stall 100%... no image at server. Another phone also couldnt upload a certain set of pictures no matter how many retries despite having uploaded and then again uploaded many hundred pictures. And I have full access to the nextcloud/server but there was nothing of value in any logs there, all I saw was the app was trying HEAD /blahblah/remot.php/webdav/blah/image_name.jpg and got 404 back. How both the app and server got to that point is interesting problem to solve.

**Comment by tobiasKaminsky** [comment]
@iskradelta which fix do you mean? Then I will 100% include it.
Do you have a "research" issue for your problem? If not, it would be great if you open one and describe when it happens, what you have tried so far.

**Comment by tobiasKaminsky** [comment]
Replacing http put is not possible as the whole internal nextcloud sync/share/etc mechanism relies on this.

**Comment by enoch85** [comment]
- [X] Translate into Swedish 100%

**Comment by AndyScherzinger** [comment]
You rock @enoch85 !!! :) 🚀

**Comment by AndyScherzinger** [comment]
1.4.0 went live on Google Play, now waiting for f-droid to publish and the screenshots PR to be merged

**Comment by enoch85** [comment]
Aah, to bad the Swedish translation didn't get in. :/

**Comment by AndyScherzinger** [comment]
Wait, what? Which ones are missing, since they should be in the release?!

**Comment by enoch85** [comment]
Transifex hadn't pulled them afaik. Checked the latest commits.

**Comment by AndyScherzinger** [comment]
Hmmm, need to check.
https://github.com/nextcloud/android/commit/ca6497d12db46f1c4175cc663e73dc1dffee21e9
I thought they were pushed on the 5th.

**Comment by enoch85** [comment]
Yup must it's there actually, but not 100% more like 80%. Anyway, 1.4.1 is here soonish ;)

**Comment by AndyScherzinger** [comment]
Are you really, really sure? As in 1.4.0 not beta? Since https://github.com/nextcloud/android/commit/ca6497d12db46f1c4175cc663e73dc1dffee21e9#diff-1c790591fb2d86b44fc896edcc7ce57e has been merged to master some time before the actual release and should thus have been shipped with 1.4.0. 0_o

**Comment by AndyScherzinger** [comment]
Which Strings are missing?

**Comment by enoch85** [comment]
Tbh I'm not 100% sure, it just feels like there are strings missing. Is the Transifex bot automated? Does it fetch strings every day? If so, it seems like there are no more strings to fetch. If not, try to fetch the latest strings manually and see if there are some translations that didn't get in. Anyway, it's not a big deal really - 1.4.1 is here in a month or so anyway :)

**Comment by enoch85** [comment]
https://github.com/nextcloud/android/commit/ca6497d12db46f1c4175cc663e73dc1dffee21e9#diff-1c790591fb2d86b44fc896edcc7ce57e

**Comment by enoch85** [comment]
@AndyScherzinger Everything seems to be translated, sorry for the noise. 

Congratulations to a great release!

**Comment by AndyScherzinger** [comment]
Better save then sorry @enoch85  :)
closing the issue and milestone since the last step (published on f-droid) is now closed off :)
