### ISSUE TITLE
Release 3.5.0 - Roadmap

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#3371]
Planned RC1: 28.01.19

**Create stable-x.y branch & use it for release**
- [x] create branch ```stable-3.5``` (needed for backport bot)
	- [x] make it protected
	- [x] set up Codacy, Drone as required status
	- [ ] enable branch to be analyzed on codacy
- [x] change 
	- [x] ```drone.yml```
	- [x] ```getBranchName.sh```
	- [x] ```analysis-wrapper.sh```

**Bump**
- [x] release new library version & use this is in app
- [x] Bump version name and version code in ```build.gradle``` files
- [x] Update ```CHANGELOG.md``` adding new features
- [x] check if code is outdated due to last supported server version ```@NextcloudServer``` annotation
- [x] bump version in MainApp
	- [x] ```OUTDATED_SERVER_VERSION``` according server (e.g. NC12)
	- [x] ```MINIMUM_SUPPORTED_SERVER_VERSION```: latest supported version - 2 (e.g. NC12 -2 = NC10)
- [x] remove support for server older ```MINIMUM_SUPPORTED_SERVER_VERSION```
- [x] add what's new slides

**Test app with all supported Android version**
- access all activities
- auto upload
- upload / download files/folders
- use external sdcard
- what's new slides correctly shown on first start

All tests on
  - [x] Android 4
  - [x] Android 5
  - [x] Android 6
  - [x] Android 7
  - [x] Android 8
  - [x] Android 9

**RC1**
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is enabled
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] Tag new version as ```rc-3.5.0-01``` with private dev key (not on github)
- [x] Build and release to Play Store as beta release and :shipit: 
- [x] Publish it on f-droid as optional release: edit metadata and open new merge request on gitlab
- [x] Verify that it is shown on f-droid (within 24h)

**RC2**
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is enabled
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] Tag new version as ```rc-3.5.0-02``` with private dev key (not on github)
- [x] Build and release to Play Store as beta release and :shipit: 
- [x] Publish it on f-droid as optional release: edit metadata and open new merge request on gitlab
- [ ] Verify that it is shown on f-droid (within 24h)

**Final Release, after two weeks time (max) of latest RC release**
- [ ]  replace screenshots (https://github.com/nextcloud/screenshots/tree/master/android/phone)
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] update translations from transifex
- [x] Test that what's new is shown correctly on upgrade
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] Tag new version as ```stable-3.5.0``` with private dev key (not on github)
- [x] Build and release to Play Store as stable release and :shipit: 
- [x] Publish it on f-droid as release: edit metadata, bump "current version" and open new merge request on gitlab
- [x] Verify that it is shown on f-droid (within 24h)

**Comment by tobiasKaminsky** [comment]
RC2 released :shipit

**Comment by AndyScherzinger** [comment]
The translations should then nevertheless be released with RC3 too. Just to see if somebody reports a problem with a translation. I am aware that this might enforce yet another translations cherry pick PR.

**Comment by tobiasKaminsky** [comment]
Good point.

**Comment by tobiasKaminsky** [comment]
3.5.0 final is releasead!

**Comment by realrufans** [comment]
Good work 👍
But 3.5.0 final? Thought it's  at 99% 🤔

**Comment by MikeZuluUSA** [comment]
Could not find any of these mentioned functions/features:

- Option to not show notifications for new media folders
- Add support for QR codes & deep links
- Direct camera upload
- Fully working Document provider
- Detail view: show complete date on click
- Show correct share error message
- Sync all downloaded

 Any help?

**Comment by realrufans** [comment]
@MikeZuluUSA  Same here .

3.5.0 says 99% complete. 
@tobiasKaminsky  says final release.

🤔

**Comment by tobiasKaminsky** [comment]
https://play.google.com/store/apps/details?id=com.nextcloud.client
it is online, maybe it takes some time. All my devices are already updated.

You can verify if you go in the app -> settings and on botton you can see the version.

@realrufans 99% complete is because this issue is still open ;-)

**Comment by realrufans** [comment]
Yes . The version is updated but not the functions.

**Comment by danielb42** [comment]
Exactly. Since yesterday (evening)'s update version string is 3.5.0, just without any of the proposed functions.

**Comment by tobiasKaminsky** [comment]
> Could not find any of these mentioned functions/features:
> 
> * Option to not show notifications for new media folders

This is shown as action in notification: https://github.com/nextcloud/android/pull/3448#issue-244247578


> * Add support for QR codes & deep links

This is shown on creating a new account:
![2019-02-14-085826](https://user-images.githubusercontent.com/5836855/52771650-b4ba8280-3036-11e9-9e13-548227434757.png)


> * Direct camera upload

Shown on "+": 
![2019-02-14-085851](https://user-images.githubusercontent.com/5836855/52771664-c439cb80-3036-11e9-95a2-ec2118ca3f4c.png)


> * Sync all downloaded

This is done in background, so you will only notice it, if you download a file, e.g. text file, change it on server and wait a bit (job is running every 15min on wifi only).

**Comment by AndyScherzinger** [comment]
So if you hit the plus button in at the bottom in the main screen you don't see a menu item "Upload from camera" in the list? If you add a new account you don't the a qr code symbol on the screen where you put in the server address? If a new media folder notification comes up it doesn't have an action to deactivate them?

**Comment by danielb42** [comment]
@AndyScherzinger nevermind, Camera Upload and QR stuff is there. Nothing new on New Folder notification however, no new settings in NC or Android settings. Where exactly should I look out for that?

**Comment by AndyScherzinger** [comment]
@danielb42 it is an action of the notification itself to hide these notifications. So you need to wait for the next new folder notification. After disabling it via the notification you can then re-enable it on the settings screen. The setting in there is only visible _after_ hiding these notifications.

**Comment by danielb42** [comment]
@AndyScherzinger alright! That workflow was just way too obscure for me. All good, thanks for the release.

**Comment by AndyScherzinger** [comment]
Yeah, we have hidden it a bit since we consider hiding these notifications an edge case so we didn't want to give it a too prominent place in the app. :)
