### ISSUE TITLE
Release 3.4.2 - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#3470]
**RC1**
- [x] Bump version name and version code in build.gradle files
- [x] update Changelog.md
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] update translations from transifex
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] Tag new version as ```rc-3.4.2-01``` with private dev key (not on github)
- [x] Build and release to Play Store as beta release and :shipit: 

**RC2**
- [x] Bump version name and version code in build.gradle files
- [x] update Changelog.md
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] update translations from transifex
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] Tag new version as ```rc-3.4.2-02``` with private dev key (not on github)
- [x] Build and release to Play Store as beta release and :shipit: 

**Final Release, after two weeks time (max) of latest RC release**
- [x]  ~~replace screenshots (https://github.com/nextcloud/screenshots/tree/master/android/phone)~~
- [x] Verify that the new version number is shown in settings
- [x] update Changelog.md
	- [x] also update Changelog.md on master branch #3506
- [x] Verify that logging is disabled
- [x] ~~update translations from transifex~~
- [x] Test that what's new is shown correctly on upgrade
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] Tag new version as ```stable-3.4.2``` with private dev key (not on github)
- [x] Build and release to Play Store as stable release and :shipit: 
- [x] Publish it on f-droid as release: edit metadata, bump "current version" and open new merge request on gitlab
- [x] Verify that it is shown on f-droid (within 24h)

Backports:
- [App](https://github.com/nextcloud/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
- [Library](https://github.com/nextcloud/android-library/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
