### ISSUE TITLE
Release 3.6.0 - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#3683]
Planned RC1: 25.03.19

**Create stable-x.y branch & use it for release**
- [x] create branch ```stable-3.6``` (needed for backport bot)
	- [x] make it protected
	- [x] set up Codacy, Drone as required status
	- [x] enable branch to be analyzed on codacy
- [x] change 
	- [x] ```drone.yml```
	- [x] ```getBranchName.sh```
	- [x] ```analysis-wrapper.sh```
	- [x] add to backport transifex stable branch, use latest two stable branches
	- [x] check that transifex still works

**Bump**
- [x] release new library version & use this is in app
- [x] Bump version name and version code in ```build.gradle``` files
- [ ] Update ```CHANGELOG.md``` adding new features
- [x] check if code is outdated due to last supported server version ```@NextcloudServer``` annotation
- [x] bump version in MainApp
	- [x] ```OUTDATED_SERVER_VERSION``` according server (e.g. NC12)
	- [x] ```MINIMUM_SUPPORTED_SERVER_VERSION```: latest supported version - 2 (e.g. NC12 -2 = NC10)
	- [x] add these versions to changelog
- [x] remove support for server older ```MINIMUM_SUPPORTED_SERVER_VERSION```
- [x] add what's new slides

**Test app with all supported Android version**
- access all activities
- auto upload
- upload / download files/folders
- use external sdcard
- what's new slides correctly shown on first start

All tests on
  - [x] Android 4
  - [x] Android 5
  - [x] Android 6
  - [x] Android 7
  - [x] Android 8
  - [x] Android 9

**RC1**
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is enabled
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] Tag new version as ```rc-3.6.0-01``` with private dev key (not on github)
- [x] Build and release to Play Store as beta release and :shipit: 
- [x] Publish it on f-droid as optional release: edit metadata and open new merge request on gitlab
- [x] Verify that it is shown on f-droid (within 24h)

**Final Release, after two weeks time (max) of latest RC release**
- [x]  replace screenshots (https://github.com/nextcloud/screenshots/tree/master/android/phone)
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] update translations from transifex
- [x] Test that what's new is shown correctly on upgrade
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] Tag new version as ```stable-3.6.0``` with private dev key (not on github)
- [x] Build and release to Play Store as stable release and :shipit: 
- [x] Publish it on f-droid as release: edit metadata, bump "current version" and open new merge request on gitlab
- [x] Verify that it is shown on f-droid (within 24h)

Backports:
- [App](https://github.com/nextcloud/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
- [Library](https://github.com/nextcloud/android-library/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

**Comment by tobiasKaminsky** [comment]
As NC16 is released on 2019-04-11, we release ~ at the same time.
So I would like to set 
OUTDATED_SERVER_VERSION = 14
MINIMUM_SUPPORTED_SERVER_VERSION = OUTDATED_SERVER_VERSION - 2 = 12

--> so we show a warning if client connects to <=14
--> we assume that every server runs at least NC12, so we can remove <NC12 compatibility checks (if any)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky Sounds good to me 👍

**Comment by tobiasKaminsky** [comment]
RC1 released :shipit:
