### ISSUE TITLE
Release 3.5.1 - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#3720]
**RC1**
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is enabled
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] Tag new version as ```rc-3.5.1-01``` with private dev key (not on github)
- [x] Build and release to Play Store as beta release and :shipit: 
- [x] Publish it on f-droid as optional release: edit metadata and open new merge request on gitlab
- [x] Verify that it is shown on f-droid (within 24h)

**RC2**
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is enabled
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] Tag new version as ```rc-3.5.1-02``` with private dev key (not on github)
- [x] Build and release to Play Store as beta release and :shipit: 
- [x] Publish it on f-droid as optional release: edit metadata and open new merge request on gitlab
- [x] ~~Verify that it is shown on f-droid (within 24h)~~

**Release**
- [x] Bump version name and version code in build.gradle files
- [x] update Changelog.md
	- [x] also update Changelog.md on master branch
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] update translations from transifex
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] Test that what's new is shown correctly on upgrade
- [x] Tag new version as `stable-3.5.1`
- [x] Build and release to Play Store as stable release and :shipit: 
- [x] ~~Verify that it is shown on f-droid (within 24h)~~

Backports:
- [App](https://github.com/nextcloud/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
- [Library](https://github.com/nextcloud/android-library/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

**Comment by tobiasKaminsky** [comment]
- [ ] release 1.3.4 NC library version

**Comment by tobiasKaminsky** [comment]
Pending: https://github.com/nextcloud/android/issues/3641

**Comment by tobiasKaminsky** [comment]
I'll do 3.5.1 RC1 tomorrow.

**Comment by AndyScherzinger** [comment]
Godspeed 👍

**Comment by AndyScherzinger** [comment]
I did the 1.3.4 lib release

**Comment by tobiasKaminsky** [comment]
RC1 released

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you check the translations? they haven't been pullled into the stable branch since 27 days ago? I thought the bot would push them to the stable branch automatically while it seems it doesn't happen or does still still have to be done manually?

**Comment by tobiasKaminsky** [comment]
Currently we have to do it manually.
But indeed this is a good idea to automatic it.

**Comment by tobiasKaminsky** [comment]
Working now, thanks to @MorrisJobke :+1: 
master: https://github.com/nextcloud/android/commit/16a0818e043e147b5b377bf2de6d06927eaaa11e
stable-3.5: https://github.com/nextcloud/android/commit/c3f073aec883dc4e0252e918ae2399c3bccfed89

**Comment by tobiasKaminsky** [comment]
3.5.1 RC2 released, especially for Transifex this is good to have an additional RC2.
As changes were really small, I think it is fine to release 3.5.1 on Friday, if nothing pops ups.

**Comment by AndyScherzinger** [comment]
> As changes were really small, I think it is fine to release 3.5.1 on Friday, if nothing pops ups.

Perfectly fine 👍
