### ISSUE TITLE
Release 3.7.1 - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#4282]
- [x] Bump version name and version code in build.gradle files
- [x] update Changelog.md
	- [x] also update Changelog.md on master branch
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] update translations from transifex
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] Test that what's new is shown correctly on upgrade
- [x] Tag new version as `stable-3.7.1`
- [x] Build and release to Play Store as stable release and :shipit: 
- [x] Verify that it is shown on f-droid (within 24h)

Backports:
- [App](https://github.com/nextcloud/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
- [Library](https://github.com/nextcloud/android-library/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

**Comment by tobiasKaminsky** [comment]
Fdroid: https://gitlab.com/fdroid/fdroiddata/merge_requests/5142
