### ISSUE TITLE
Release 3.8.0 - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#4288]
Planned RC1: 20.08.19

**Create stable-x.y branch & use it for release**
- [x] create branch ```stable-3.8``` (no ".x" anymore due to backport bot)
	- [x] make it protected
	- [x] set up Codacy, Drone as required status
	- [x] enable branch to be analyzed on codacy
- [x] change 
	- [x] ```drone.yml```
	- [x] ```getBranchName.sh```
	- [x] ```analysis-wrapper.sh```
	- [x] add to backport transifex stable branch, use latest two stable branches
	- [x] check that transifex bot still works

**Bump**
- [x] release new library version with rc1 tag & use this is in app
- [x] release new library version with rc2 tag & use this is in app
- [x] release new library version with rc3 tag & use this is in app
- [x] release new library version with rc4 tag & use this is in app
- [x] Bump version name and version code in ```build.gradle``` files
- [x] Update ```CHANGELOG.md``` adding new features
- [x] check if code is outdated due to last supported server version ```@NextcloudServer``` annotation
- [x] bump version in MainApp
	- [x] ```OUTDATED_SERVER_VERSION``` according https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule (e.g. NC13)
	- [x] ```MINIMUM_SUPPORTED_SERVER_VERSION```: latest end of life + 1 year (e.g. NC13 end of life 2019-02-28 + 1 year = 2020-02-28)
	- [x] add these versions to changelog
- [x] remove support for server older ```MINIMUM_SUPPORTED_SERVER_VERSION```
- [x] add what's new slides

**Test app with all supported Android version**
- access all activities
- auto upload
- upload / download files/folders
- use external sdcard
- what's new slides correctly shown on first start

All tests on
  - [x] Android 4
  - [x] Android 5
  - [x] Android 6
  - [x] Android 7
  - [x] Android 8
  - [x] Android 9

**RC1**
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is enabled
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] Tag new version as ```rc-3.8.0-01``` with private dev key (not on github)
- [x] Build and release to Play Store as beta release and :shipit: 
- [x] Publish it on f-droid as optional release: edit metadata and open new merge request on gitlab
- [x] Verify that it is shown on f-droid (within 24h)

**RC2**
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is enabled
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] Tag new version as ```rc-3.8.0-02``` with private dev key (not on github)
- [x] Build and release to Play Store as beta release and :shipit: 
- [x] Publish it on f-droid as optional release: edit metadata and open new merge request on gitlab
- [x] Verify that it is shown on f-droid (within 24h)

**RC3**
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is enabled
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] Tag new version as ```rc-3.8.0-03``` with private dev key (not on github)
- [x] Build and release to Play Store as beta release and :shipit: 
- [x] Publish it on f-droid as optional release: edit metadata and open new merge request on gitlab
- [x] Verify that it is shown on f-droid (within 24h)

**RC4**
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is enabled
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] Tag new version as ```rc-3.8.0-04``` with private dev key (not on github)
- [x] Build and release to Play Store as beta release and :shipit: 
- [x] Publish it on f-droid as optional release: edit metadata and open new merge request on gitlab
- [x] Verify that it is shown on f-droid (within 24h)

**Final Release, after two weeks time (max) of latest RC release**
- [x] ~~set library to final tag~~
- [x]  replace screenshots (https://github.com/nextcloud/screenshots/tree/master/android/phone)
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] update translations from transifex
- [x] Test that what's new is shown correctly on upgrade
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] Tag new version as ```stable-3.8.0``` with private dev key (not on github)
- [x] Build and release to Play Store as stable release and :shipit: 
- [x] Publish it on f-droid as release: edit metadata, bump "current version" and open new merge request on gitlab
- [x] Verify that it is shown on f-droid (within 24h)

Backports:
- [App](https://github.com/nextcloud/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
- [Library](https://github.com/nextcloud/android-library/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

Open PRs:
- [Milestone](https://github.com/nextcloud/android/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Nextcloud+App+3.8.0%22)

**Comment by AndyScherzinger** [comment]
My take, to be discussed @tobiasKaminsky @ezaquarii, PRs we should try to get into `3.8.0 RC1` (within the next 2 week):

* [ ] Fix upload and delete to actually delete #4287
* [ ] FIDO U2F Support #4286
* [ ] New logger implementation #4275
* [ ] Fix local state if fragment is initialized before services #4262
* [ ] Fix upload list comparator to make it respect the comparator contract #4245
* [ ] Fix unsafe updates to current upload #4244
* [ ] Provide a banal 'paste' postmessage implementation. #4189
* [ ] Check if app is excluded from battery optimization #3589

**Comment by tobiasKaminsky** [comment]
I am trying to review all PRs (also the other labeled 2. to review), but currently other things keep me away :/

While this is a nice idea to have this list, we will not delay the release if any PR is not in.

**Comment by tobiasKaminsky** [comment]
RC2 released

**Comment by tobiasKaminsky** [comment]
RC3 released, hopefully the last one :crossed_fingers:

**Comment by tobiasKaminsky** [comment]
Tomorrow/Thursday I will release RC4, and Friday next week final release, so we can celebrate on Conf ;-)

**Comment by tobiasKaminsky** [comment]
RC4 released

**Comment by Valdnet** [comment]
@tobiasKaminsky Shouldn't this bug #4401 be fixed before releasing the final version?

**Comment by tobiasKaminsky** [comment]
Fixed via https://github.com/nextcloud/android/pull/4485

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky stable release is running on a RC release of the lib... https://github.com/nextcloud/android/blob/3398097d84ffd76f73a2c50f9bd60a5e6127e1bc/build.gradle#L60

**Comment by tobiasKaminsky** [comment]
I will change this with 3.8.1
