### ISSUE TITLE
Release 3.7.2 - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#4335]
- [x] Bump version name and version code in build.gradle files
- [x] update Changelog.md
	- [x] also update Changelog.md on master branch
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] update translations from transifex
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] Test that what's new is shown correctly on upgrade
- [x] Tag new version as `stable-3.7.2`
- [x] Build and release to Play Store as stable release and :shipit: 
- [ ] Verify that it is shown on f-droid (within 24h)

Backports:
- [App](https://github.com/nextcloud/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
- [Library](https://github.com/nextcloud/android-library/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

**Comment by AndyScherzinger** [comment]
F-Droid merge request: https://gitlab.com/fdroid/fdroiddata/merge_requests/5265 (already merged), so awaiting build & publish

**Comment by AndyScherzinger** [comment]
@Bubu 3.7.2 has been merged 6 days ago and still hasn't been published yet :( 
(We are already having 3.8.0 RC1 out the door)

**Comment by Bubu** [comment]
On August 22, 2019 6:52:10 PM GMT+02:00, Andy Scherzinger <notifications@github.com> wrote:
>@Bubu 3.7.2 has been merged 6 days ago and still hasn't been published
>yet :( 
>(We are already having 3.8.0 RC1 out the door)

Soemthing was stuck but 3.7.2 is published now.

**Comment by AndyScherzinger** [comment]
> Soemthing was stuck but 3.7.2 is published now.

Thank a lot @Bubu! ❤️ (While https://f-droid.org/en/packages/com.nextcloud.client/ still showss 3.71., at least to me, enforced browser refresh/cache)

**Comment by Bubu** [comment]
On August 22, 2019 7:15:19 PM GMT+02:00, Andy Scherzinger <notifications@github.com> wrote:
>> Soemthing was stuck but 3.7.2 is published now.>
>>
>Thank a lot @Bubu! ❤️ (While
>https://f-droid.org/en/packages/com.nextcloud.client/ still showss
>3.71., at least to me, enforced browser refresh/cache)>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/nextcloud/android/issues/4335#issuecomment-523995730

🙄, thanks for the heads up.

**Comment by AndyScherzinger** [comment]
Now available on f-droid
