### ISSUE TITLE
Release 3.8.1 - Roadmap

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4569]
- [x] Bump version name and version code in build.gradle files
- [x] update Changelog.md
	- [ ] also update Changelog.md on master branch
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] update translations from transifex
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] Test that what's new is shown correctly on upgrade
- [x] Tag new version as `stable-3.8.1`
- [x] Build and release to Play Store as stable release and :shipit: 
- [ ] Verify that it is shown on f-droid (within 24h)

Backports:
- [App](https://github.com/nextcloud/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
- [Library](https://github.com/nextcloud/android-library/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

Library
- [x] backport https://github.com/nextcloud/android-library/pull/338
- [x] release new 1.6.1-rc1 version

**Comment by tobiasKaminsky** [comment]
RC2 released

**Comment by ilioNaglo** [comment]
17 days later and this version is still not on F-Droid.  unable to upload in version 3.8.0 or 3.8.1.  reverted to 2.7.3 which works.

**Comment by AndyScherzinger** [comment]
F-droid is handled by f-droid themselves, nothing 2e can do about it.

Pinging @Bubu for support ❤️

**Comment by Bubu** [comment]
@AndyScherzinger Tobias opened the MR for F-Droid 3 days ago, it was now merged about an hour ago. It will be published in hopefully 1-2 days.
Be patient.

(3.8.0 is available for quite a while now I think/)
