### ISSUE TITLE
Release 3.9.0 - Roadmap

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4584]
Planned RC1: 28.10.19

**Bump**
- [x] Update version on master to next major version
- [x] bump version in MainApp
	- [x] ```OUTDATED_SERVER_VERSION``` according https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule (e.g. NC12)
	- [x] ```MINIMUM_SUPPORTED_SERVER_VERSION```: latest end of life + 1 year (e.g. NC13 end of life 2019-02-28 + 1 year = 2020-02-28)
	- [x] add these versions to changelog
- [x] check if code is outdated due to last supported server version ```@NextcloudServer``` annotation
- [x] remove support for server older ```MINIMUM_SUPPORTED_SERVER_VERSION```
- [x] do the same on library

**Create stable-x.y branch & use it for release**
- [x] create branch ```stable-3.9``` (no ".x" anymore due to backport bot)
	- [x] enable branch to be analyzed on codacy
- [x] change on App
	- [x] ```drone.yml```
	- [x] ```getBranchName.sh```
	- [x] ```analysis-wrapper.sh```
	- [x] check that transifex bot still works
- [x] change on Lib, if backport is needed
	- [x] create branch stable-1.7 (no ".x" anymore due to backport bot) 
	- [x] ```drone.yml```
	- [x] ```getBranchName.sh```
	- [x] ```analysis-wrapper.sh```

**Test app with all supported Android version**
- access all activities
- auto upload
- upload / download files/folders
- use external sdcard
- what's new slides correctly shown on first start

All tests on
  - [x] Android 4
  - [x] Android 5
  - [x] Android 6
  - [x] Android 7
  - [x] Android 8
  - [x] Android 9

**RC1**
- [x] Bump version code in ```build.gradle``` files
- [x] add what's new slides
- [x] release new library version with rc1 tag & use this is in app
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is enabled
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] Tag new version as ```rc-x.y.z-01``` with private dev key (not on github)
- [x] Build and release to Play Store as beta release and :shipit: 
- [x] Publish it on f-droid as optional release: edit metadata and open new merge request on gitlab
- [x] Verify that it is shown on f-droid (within 24h)

**Final Release, after two weeks time (max) of latest RC release**
- [x] set library to final tag
- [x] Update ```CHANGELOG.md``` adding new features
- [x]  replace screenshots (https://github.com/nextcloud/screenshots/tree/master/android/phone)
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] update translations from transifex
- [x] Test that what's new is shown correctly on upgrade
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] Tag new version as ```stable-x.y.z``` with private dev key (not on github)
- [x] Build and release to Play Store as stable release and :shipit: 
- [x] Publish it on f-droid as release: edit metadata, bump "current version" and open new merge request on gitlab
- [x] Verify that it is shown on f-droid (within 24h)

Backports:
- [App](https://github.com/nextcloud/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
- [Library](https://github.com/nextcloud/android-library/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

Open PRs:
- [Milestone](https://github.com/nextcloud/android/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Nextcloud+App+3.7.0%22)

**Comment by tobiasKaminsky** [comment]
@jospoortvliet

**Comment by tobiasKaminsky** [comment]
3.9.0 RC1 released

**Comment by tobiasKaminsky** [comment]
3.9.0 released

**Comment by AndyScherzinger** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/5935
