### ISSUE TITLE
Migrate user account management to UserAccountManager

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#4676]
### Situation

Currently user account can be represented by 4 different types:

* `android.accounts.Account`
* `com.owncloud.android.lib.common.OwnCloudAccount`
* `String` id
* `int` id

Accounts are being juggled in activities that try to track which account is currently active and perform ad-hoc reinitialization of UI on change.

The logic responsible for reconciliation of currently selected account and UI state is virtually impossible to track due to large amount of flags, conditions and out-of-band state modification. 

Additionally, we discovered some issues with android account manager, causing accounts to disappear from the `android.accounts.AccountManager` on phones that allow installing application on external storage.

### Solution

1. Make `UserAccountManager` a single point of truth regarding currently selected account
2. Eliminate ad-hoc UI patching in life cycle callbacks
3. Switch application to new unified account type
4. Unify account representation under one type
5. Deprecate `OwnCloudAccount` or at least make it private implementation detail

### Roadmap

Due to current state of code, extensive refactoring and cleanup around account handling is necessary, as it contains too much state mutation dispersed through many functional areas.
Managing risk in such environment is not economical.

Proposal (incomplete):

1. [ ] Deprecate `setAccount` and `onAccountSet` logic
2. [ ] Eliminate account status flags from `BaseActivity` and derived classes
3. [ ] Refactor all activities performing or reacting to account switch to stop using `setAccount` and manually calling `onAccountSet` callback out of band.
4. [ ] Extend `UserAccountManager` with notification API, allowing UI layer to react on account swap
5. [ ] Finish activities stack and restart with new account instead of trying to switch internal state
Enable assumption that account cannot change while being inside lifecycle activity. 
6. [ ] Start migrating to new account type (details to follow...)

**Comment by tobiasKaminsky** [comment]
Very good approach!
I guess the idea of OwnCloudAccount is to handle the most basic infos within library, so that other apps can also use this. Something similar is OCFile (in our app) vs RemoteFile (in library) for representing a server file.
