### ISSUE TITLE
Release 3.11.0 - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#4779]
Planned RC1: 02.03.20

**Create stable-x.y branch & use it for release**
- [x] create branch ```stable-3.11``` (no ".x" anymore due to backport bot)
	- [x] make it protected
	- [x] set up Codacy, Drone as required status
	- [x] enable branch to be analyzed on codacy
- [x] change on App
	- [x] ```drone.yml```
	- [x] ```getBranchName.sh```
	- [x] ```analysis-wrapper.sh```
	- [x] add to backport transifex stable branch, use latest two stable branches
	- [x] check that transifex bot still works
- [x] change on Lib
	- [x] ```drone.yml```
	- [x] ```getBranchName.sh```
	- [x] ```analysis-wrapper.sh```

**Bump**
- [x] release new library version with rc1 tag & use this is in app
- [x] release new SSO if needed
- [x] Bump version name and version code in ```build.gradle``` files
- [x] Update ```CHANGELOG.md``` adding new features
- [x] Update version on master to next major version
- [x] ~~check if oldest Android version is EOL by Google and user usage <= 0.5% and drop it if so (**--> drop Android 4.1**) #5594~~
- [x] ~~With `minSDK=17` #4480 should be reactivated to get that depedency updated (which requires Android `minSDK=17`)~~
- [ ] check if code is outdated due to last supported server version ```@NextcloudServer``` annotation
- [ ] bump version in MainApp
	- [ ] ```OUTDATED_SERVER_VERSION``` according https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule (e.g. NC12)
	- [ ] ```MINIMUM_SUPPORTED_SERVER_VERSION```: latest end of life + 1 year (e.g. NC13 end of life 2019-02-28 + 1 year = 2020-02-28)
	- [ ] add these versions to changelog
- [ ] remove support for server older ```MINIMUM_SUPPORTED_SERVER_VERSION```
- [ ] do the same on library
- [x] add what's new slides

**Test app with all supported Android version**
- access all activities
- auto upload
- upload / download files/folders
- use external sdcard
- what's new slides correctly shown on first start

All tests on
  - [ ] Android 4
  - [ ] Android 5
  - [ ] Android 6
  - [ ] Android 7
  - [ ] Android 8
  - [ ] Android 9
  - [ ] Android 10

**RC1**
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is enabled
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] Tag new version as ```rc-3.11.0-01``` with private dev key (not on github)
- [x] Build and release to Play Store as beta release and :shipit: 
- [x] Publish it on f-droid as optional release: edit metadata and open new merge request on gitlab
- [ ] Verify that it is shown on f-droid (within 24h)

**Final Release, after two weeks time (max) of latest RC release**
- [ ] set library to final tag
- [ ]  replace screenshots (https://github.com/nextcloud/screenshots/tree/master/android/phone)
- [ ] Verify that the new version number is shown in settings
- [ ] Verify that logging is disabled
- [ ] update translations from transifex
- [ ] Test that what's new is shown correctly on upgrade
- [ ] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [ ] Tag new version as ```stable-3.11.0``` with private dev key (not on github)
- [ ] Build and release to Play Store as stable release and :shipit: 
- [ ] Publish it on f-droid as release: edit metadata, bump "current version" and open new merge request on gitlab
- [ ] Verify that it is shown on f-droid (within 24h)

Backports:
- [App](https://github.com/nextcloud/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
- [Library](https://github.com/nextcloud/android-library/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

Open PRs:
- [Milestone](https://github.com/nextcloud/android/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Nextcloud+App+3.11.0%22)

Marketing:
@jospoortvliet

**Comment by tobiasKaminsky** [comment]
RC1 released

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky 
> check if oldest Android version is EOL by Google and user usage <= 0.5% and drop it if so (--> drop Android 4.1)

<img width="683" alt="2020-03-06 10_27_16-Statistics - Nextcloud - Google Play Console" src="https://user-images.githubusercontent.com/1315170/76070651-2b555580-5f95-11ea-90f2-3cd7b0ccfba2.png">

--> Android 4.1 at 0,1% --> Drop 4.1

**Comment by tobiasKaminsky** [comment]
RC2 released

**Comment by tobiasKaminsky** [comment]
RC3 released

**Comment by tobiasKaminsky** [comment]
RC4 released

**Comment by InfamousUser** [comment]
Why does the official blog post say: "This version of the nextcloud Android client (version 3.11.0) is supported on Android 4.1 and newer." when I just read here that 4.1 it has been dropped?

**Comment by tobiasKaminsky** [comment]
Plan was to drop it already with this version, but 4.1 is still supported:
https://github.com/nextcloud/android/blob/stable-3.11/build.gradle#L132

**Comment by AndyScherzinger** [comment]
We missed to drop it so 3.11 is the last feature release supporting 4.1, so 3.12 will support 4.2+
