### ISSUE TITLE
Release 3.9.1 - Roadmap

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4887]
Planned RC: 26.11.19 

- [ ] Bump version name and version code in build.gradle files
- [ ] update Changelog.md
	- [ ] also update Changelog.md on master branch
- [ ] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [ ] update translations from transifex
- [ ] Verify that the new version number is shown in settings
- [ ] Verify that logging is disabled
- [ ] Test that what's new is shown correctly on upgrade
- [ ] Tag new version as `stable-x.y.Z`
- [ ] Build and release to Play Store as stable release and :shipit: 
- [ ] Verify that it is shown on f-droid (within 24h)

Backports:
- [App](https://github.com/nextcloud/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
- [Library](https://github.com/nextcloud/android-library/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
