### ISSUE TITLE
Release 3.9.1 - Roadmap

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4892]
- [x] Bump version name and version code in build.gradle files
- [x] update Changelog.md
	- [x] also update Changelog.md on master branch
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] update translations from transifex
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [ ] Test that what's new is shown correctly on upgrade
- [ ] Tag new version as `stable-x.y.Z`
- [ ] Build and release to Play Store as stable release and :shipit: 
- [ ] Verify that it is shown on f-droid (within 24h)

Backports:
- [App](https://github.com/nextcloud/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
- [Library](https://github.com/nextcloud/android-library/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
