### ISSUE TITLE
Enhance Dark Mode

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#5353]
@jancborchardt and me went over dark mode and found some things to do

- [x] #5739 heading, blue background: text should stay white
- [x] #5739 triangle in drawer -> white
- [x] #5739 share icons: more users -> white
- [x] #5739 file detail sharing: above act/sharing -> white line should be same like receive external files line
- [x] activity/notifications: 
    - [x] invert all except "file_created" and "file_deleted" 
    - [x] remove background circle
    - [x] remove white border from shared_via_link
- [x] #5739 notifications: button: 
    - [x] #5739 light: background (light gray), no border
    - [x] #5739 dark: background: ligth gray, no border
- [x] #5739 + button: white color
- [x] long press: 
    - [x] weird header, status bar same dark gray
    - [x] on selected item: subline lighter
    - [x] highlight: darker
- [x] #5739 In the file list, the favorite icon needs a dark outline instead of white. Also the "Person" icon on the right should be light (very barely visible now): 
  ![Dark mode user share icon in file list and favorite icon](https://user-images.githubusercontent.com/925062/77441538-d49ba880-6de9-11ea-98b9-664eab98d9bd.png)
- [x] #5739 The triangle for account switching in the sidebar should be light:
  ![Dark mode triangle in sidebar](https://user-images.githubusercontent.com/925062/77441539-d5343f00-6de9-11ea-9885-543afd2d8420.png)
- [x] #5739 The lines in the "Add" menu should be dark as well:
  ![Dark mode add menu lines should be dark as well](https://user-images.githubusercontent.com/925062/77441529-d2d1e500-6de9-11ea-8dfe-46f5fd80ad7d.png)
- [x] #5739 The refresh spinner could be dark as well?
  ![Dark mode refresh spinner should be dark too](https://user-images.githubusercontent.com/925062/77441532-d4031200-6de9-11ea-9ca7-78a37c6982cc.png)
- [x] ~~Toasts could be dark as well:~~
  ![Dark mode toasts should also be dark](https://user-images.githubusercontent.com/925062/77441540-d5343f00-6de9-11ea-97ff-338f8c338e4d.png)
- [x] The header color in the app switcher looks off – this is not themed:
  ![Dark mode header color looks off](https://user-images.githubusercontent.com/925062/77441535-d4031200-6de9-11ea-98fa-7d555ed01424.png)
@AndyScherzinger @dan0xii maybe you have time and want to help out? :heart:

**Comment by AndyScherzinger** [comment]
> remove background circle

So how do we "re-colorize" the icons? We added the circle so the icons would just get visible again for dark them (is that the invert task?)

**Comment by tobiasKaminsky** [comment]
Yes.
All icons are black, so we invert them on dark mode.
File_created (green +) and file_deleted (red x) can remain the same.

**Comment by moviuro** [comment]
Hi, should the markdown editor also get a dark theme? (or should that be reported in another GitHub project?)

With Nexcloud for Android Beta 3.11.0 RC3, the editor defaults to black text on white background, when e.g. editing the Readme.md file in a directory.

**Comment by tobiasKaminsky** [comment]
> Hi, should the markdown editor also get a dark theme?

Yes, it should :-)





> or should that be reported in another GitHub project?)

Depends: when viewing the readme / folder info, then it is within this repo.
When editing a text file, then it is https://github.com/nextcloud/text/

**Comment by moviuro** [comment]
> Depends: when viewing the readme / folder info, then it is within this repo.
> When editing a text file, then it is https://github.com/nextcloud/text/

Specifically when I edit a Readme.md file in the Android app, the text zone is black on white. See https://sco.popho.be/s/Z2ANq6m22jTaRfX

**Comment by tobiasKaminsky** [comment]
Which version do you use?
Can you try 3.11RC4 which is available via Fdroid/play store beta program?

For me it looks good:
![2020-03-24-105810](https://user-images.githubusercontent.com/5836855/77412578-5c6bbd80-6dbe-11ea-916c-0349a79a3c4d.png)

**Comment by moviuro** [comment]
I have the 3.11.0RC4 too. I was *editing* the mardown file, not just viewing it. What happens when you tap the pencil icon at the bottom right?

**Comment by tobiasKaminsky** [comment]
Then the text editor is launched, which is then an issue of the above repo :-)

**Comment by jancborchardt** [comment]
Here are some screenshots of the specific points to illustrate what is left to do:

- [ ] In the file list, the favorite icon needs a dark outline instead of white. Also the "Person" icon on the right should be light (very barely visible now):
  ![Dark mode user share icon in file list and favorite icon](https://user-images.githubusercontent.com/925062/77441538-d49ba880-6de9-11ea-98b9-664eab98d9bd.png)
- [ ] The triangle for account switching in the sidebar should be light:
  ![Dark mode triangle in sidebar](https://user-images.githubusercontent.com/925062/77441539-d5343f00-6de9-11ea-9885-543afd2d8420.png)
- [ ] The lines in the "Add" menu should be dark as well:
  ![Dark mode add menu lines should be dark as well](https://user-images.githubusercontent.com/925062/77441529-d2d1e500-6de9-11ea-8dfe-46f5fd80ad7d.png)
- [ ] The refresh spinner could be dark as well?
  ![Dark mode refresh spinner should be dark too](https://user-images.githubusercontent.com/925062/77441532-d4031200-6de9-11ea-9ca7-78a37c6982cc.png)
- [ ] Toasts could be dark as well:
  ![Dark mode toasts should also be dark](https://user-images.githubusercontent.com/925062/77441540-d5343f00-6de9-11ea-97ff-338f8c338e4d.png)
- [ ] The header color in the app switcher looks off – this is not themed:
  ![Dark mode header color looks off](https://user-images.githubusercontent.com/925062/77441535-d4031200-6de9-11ea-98fa-7d555ed01424.png)

**Comment by dan0xii** [comment]
I've made a start on these issues in [#5353-dm](https://github.com/nextcloud/android/tree/5353-dm). https://github.com/nextcloud/android/commit/f868b5a3c3871794f03cea25fd4892da88466a1c fixes three from Jan's post at least and I'm working on the rest.

**Comment by AndyScherzinger** [comment]
> The lines in the "Add" menu should be dark as well:

@jancborchardt why? In the light theme they are dark (=text color), so either 
* they stay light (for the dark) theme or
* get removed completely

The dividers are there to divide the menu item groups. Other than that they should be rather 
* light grey (for dark and light theme)
* have a padding on the left and start with the text, see GDrive for example
![Screenshot_20200325-112328_Drive](https://user-images.githubusercontent.com/1315170/77526637-32340180-6e8b-11ea-86ec-f9ac8c188a9b.png)

So other than that I'd also propose to:
* not tint the icons anymore in this bottom menu(s) but rather use the grey version (except for the doc-types (like we do now for collabora/OO
*

**Comment by AndyScherzinger** [comment]
or we raise the margin between the menu item groups (like in the drawer menu, for consistency)

**Comment by jancborchardt** [comment]
@AndyScherzinger the lines should just not be so bright, but more like the color of the subline in the file list, or the 3-dot icon. :) They are only dividers, not to call attention to themselves.

**Comment by AndyScherzinger** [comment]
@jancborchardt 

> the lines should just not be so bright, but more like the color of the subline in the file list, or the 3-dot icon. :) They are only dividers, not to call attention to themselves.

DONE 👍 

> Toasts could be dark as well:

Let's discuss this one because Android does it "the other way around", so on light theme toasts are dark and on dark themes toast are light. This is done by Android OS, so I'd keep it this way (since that is standard Android behavior/coloring)

**Comment by dan0xii** [comment]
> activity/notifications:
>
>   invert all except "file_created" and "file_deleted"

I don't understand what's meant here.

>   remove background circle

Done. 

![ss1](https://user-images.githubusercontent.com/1926270/78449971-24446480-7673-11ea-9495-9d24494bc53e.png)


>   remove white border from shared_via_link

Is "Copy link" below the icon you're referring to?

![ss2](https://user-images.githubusercontent.com/1926270/78449989-3d4d1580-7673-11ea-92b5-3cce015e808e.png)

**Comment by AndyScherzinger** [comment]
@dan0xii you need to add a new, second link icon, the one used so far has the stroke color on purpose since it is also used as an overlay on images.

**Comment by AndyScherzinger** [comment]
> invert all except "file_created" and "file_deleted"

@dan0xii all icons except the ones for the two activities mentioned above are black and thus need to be inverted before display. The icons are fetched from the server for each activity.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky 

> invert all except "file_created" and "file_deleted"

Any idea how to do this? I found examples for Glide 4, but we are still stuck on Glide 3 due to the large efforts needed to migrate to 4. Any ideas how to solve this for our case?

**Comment by tobiasKaminsky** [comment]
Should be something like
`
myImageView.setColorFilter(Color.WHITE, PorterDuff.Mode.XOR);
`

**Comment by jancborchardt** [comment]
> > activity/notifications:
> > invert all except "file_created" and "file_deleted"
> 
> I don't understand what's meant here.

@dan0xii if you look at the screenshot you took, on the left next to "You commented test" there is a very faintly visible black "comment" icon. :) In dark mode, that should be inverted to be light.
In fact all others of this Activity timeline need to be inverted as they are black, except file_created and file_deleted since they are green and red respectively and should keep their color even in dark mode.

**Comment by tobiasKaminsky** [comment]
@jancborchardt as we get these images as svg from server, do you have an idea how to invert them?
My idea, to invert the entire image did not worked out:
![2020-06-05-090611](https://user-images.githubusercontent.com/5836855/83847007-d0eea100-a70b-11ea-9b02-49bcd1bed74c.png)
