### ISSUE TITLE
Release 3.12.0 - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#5644]
Planned RC1: 27.04.2020

**Bump (do this when creating new roadmap)**
- [x] create milestone
- [x] bump version in MainApp
	- [x] ```OUTDATED_SERVER_VERSION``` according https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule (e.g. NC12)
	- [x] ```MINIMUM_SUPPORTED_SERVER_VERSION```: latest end of life + 1 year (e.g. NC13 end of life 2019-02-28 + 1 year = 2020-02-28)
	- [x] add these versions to changelog
- [x] App
    - [x] check if code is outdated due to last supported server version ```@NextcloudServer``` annotation
    - [x] remove support for server older ```MINIMUM_SUPPORTED_SERVER_VERSION```
- [x] Library
    - [x] check if code is outdated due to last supported server version ```@NextcloudServer``` annotation
    - [x] remove support for server older ```MINIMUM_SUPPORTED_SERVER_VERSION```
- [x] check if oldest Android version is EOL by Google and user usage <= 0.5% and drop it if so
  - [x] search for usage of Build.VERSION_CODES.xy
  - [x] announce it in changelog
- [x] Update version on master to next major version

**Create stable-3.12 branch & use it for release (when releasing RC1)**
- [x] create branch ```stable-3.12```
	- [x] enable branch to be analyzed on codacy
- [x] change on App
	- [x] ```drone.yml```
	- [x] ```getBranchName.sh```
	- [x] ```analysis-wrapper.sh```
	- [x] check that transifex bot still works
- [x] change on Lib
    - [x] create branch stable-2.x
    - [x] enable branch to be analyzed on codacy
	- [x] ```drone.yml```
	- [x] ```getBranchName.sh```
	- [x] ```analysis-wrapper.sh```

**Test app with all supported Android version**
- access all activities
- auto upload
- upload / download files/folders
- use external sdcard
- what's new slides correctly shown on first start

All tests on
  - [x] Android 4
  - [x] Android 5
  - [x] Android 6
  - [x] Android 7
  - [x] Android 8
  - [x] Android 9
  - [x] Android 10

**RC1**
- [x] Bump version code in ```build.gradle``` file
- [x] add what's new slides
- [x] replace screenshots (https://github.com/nextcloud/screenshots/tree/master/android/phone)
- [x] release new library version with rc-2.x.y-01 tag & use this is in app
- [x] release new SSO if needed
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is enabled
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] release with fastlane: creates GH release, uploads to Gplay, creates Gitlab MR for F-Droid
- [x] Verify that it is shown on [F-Droid](https://f-droid.org/de/packages/com.nextcloud.client/) (within 24h)
- [x] inform marketing about changelog and expected release date

**Final Release, after two weeks time (max) of latest RC release**
- [x] Bump version code in ```build.gradle``` file
- [x] set library to final tag
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] Test that what's new is shown correctly on upgrade
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] release with fastlane: creates GH release, uploads to Gplay, creates Gitlab MR for F-Droid
- [x] Verify that it is shown on [F-Droid](https://f-droid.org/de/packages/com.nextcloud.client/) (within 24h)

** After release**
- x.y.-1
  - [x] delete ```stable-3.11``` branch
- x.y.1
  - [x] create milestone 3.12.1
  - [x] schedule 3.12.1 RC1 3 weeks after stable, release ~4 weeks
  - [x] create overview issue
- x.y+1
  - [x] create milestone 3.13.0
  - [x] create overview issue & adjust date, handle bumps

Backports:
- [App](https://github.com/nextcloud/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
- [Library](https://github.com/nextcloud/android-library/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

Open PRs:
- [Milestone](https://github.com/nextcloud/android/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Nextcloud+App+3.12.0%22)

Marketing:
@jospoortvliet

**Comment by tobiasKaminsky** [comment]
RC 2 released :shipit:

**Comment by tobiasKaminsky** [comment]
RC3 released.
Sorry for the delay…

**Comment by tobiasKaminsky** [comment]
Final relased

**Comment by AndyScherzinger** [comment]
All follow-up release issues, bumps etc. are DONE.
